"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  ArrowRight,
  ArrowLeft,
  Mail,
  Building2,
  FileText,
  Edit3,
  Eye,
  Send,
  Copy,
  Check,
  ChevronLeft,
  ChevronRight,
  User,
  AtSign,
  Loader2,
  AlertTriangle,
} from "lucide-react";
import { toast } from "sonner";
import { ThemeToggle } from "@/components/ThemeToggle";

const TPAMailLogo = () => (
  <div className="flex items-center gap-4 mb-6">
    <div className="relative group">
      <div className="absolute -inset-1 bg-gradient-to-r from-[#00DFB8] via-[#00B894] to-[#00A085] rounded-2xl blur opacity-25 group-hover:opacity-40 transition duration-1000"></div>
      <div className="relative w-12 h-12 bg-gradient-to-br from-[#00DFB8] to-[#00B894] rounded-xl flex items-center justify-center shadow-lg">
        <Mail className="w-6 h-6 text-white" />
        <div className="absolute -bottom-1 -right-1 w-4 h-4 bg-gradient-to-r from-[#00DFB8] to-[#00E6C7] rounded-full border-2 border-white shadow-lg flex items-center justify-center">
          <div className="w-1.5 h-1.5 bg-white rounded-full"></div>
        </div>
      </div>
    </div>
    <div>
      <h1 className="text-2xl font-bold bg-gradient-to-r from-gray-900 to-gray-600 dark:from-gray-100 dark:to-gray-400 bg-clip-text text-transparent">
        TPA Mail
      </h1>
      <p className="text-xs text-gray-500 dark:text-gray-400">The Payments Association</p>
    </div>
  </div>
);

// Email validation function
const validateEmail = (template) => {
  const issues = [];
  const warnings = [];
  
  // Critical issues (must fix)
  if (template.body.includes('**XXX**') || template.body.includes('XXX')) {
    issues.push('Contains placeholder **XXX** that needs to be replaced');
  }
  
  if (!template.body.includes('Hi ')) {
    issues.push('Missing greeting');
  }
  
  // Warnings (should review)
  if (template.body.length < 150) {
    warnings.push('Email seems quite short (under 150 characters)');
  }
  
  if (template.body.length > 1000) {
    warnings.push('Email is quite long (over 1000 characters) - consider shortening');
  }
  
  const wordCount = template.body.split(/\s+/).filter(w => w.length > 0).length;
  if (wordCount < 50) {
    warnings.push(`Email has only ${wordCount} words - consider adding more detail`);
  }
  
  if (!template.body.toLowerCase().includes('article') && !template.body.toLowerCase().includes('commentary')) {
    warnings.push('No mention of article or commentary found');
  }
  
  if (!template.body.toLowerCase().includes('deadline')) {
    warnings.push('No deadline mentioned in email');
  }
  
  const hasContactDetails = template.body.toLowerCase().includes('let me know') || 
                           template.body.toLowerCase().includes('contact') ||
                           template.body.toLowerCase().includes('information');
  if (!hasContactDetails) {
    warnings.push('Consider adding a call-to-action or contact invitation');
  }
  
  return { issues, warnings };
};

// Generate company-focused email template
const generateCompanyEmailTemplate = (company, articleData) => {
  return {
    subject: `TPA Request`,
    body: `Hi **XXX**,

I hope you're well

I'm a data journalist at The Payments Association - I'm writing to introduce myself and offer you the opportunity to provide commentary for my article on ${articleData.title}.

[ARTICLE SUMMARY WILL BE GENERATED BY AI]

For context: Article commentary is ~70 word statement which is included in the 'Industry Voices' section of our articles - along with the person's name, job title, and company - which are shared with our entire membership and through our social media channels.

The deadline for commentary is **XXX**

Let me know if you would like any more information

Many thanks,`,
  };
};

export default function EmailTemplates({
  articleData = {},
  selectedMembers = [],
  onBack,
  onContinue,
}) {
  const [emailTemplates, setEmailTemplates] = useState(() =>
    selectedMembers.map((company) => ({
      companyId: company.id,
      company,
      contactName: "",
      contactRole: "",
      contactEmail: "",
      template: {
        subject:
          generateCompanyEmailTemplate(company, articleData).subject || "",
        body: generateCompanyEmailTemplate(company, articleData).body || "",
      },
      isEdited: false,
      isApproved: false,
    }))
  );

  const [currentEmailIndex, setCurrentEmailIndex] = useState(0);
  const [copiedField, setCopiedField] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const currentTemplate = emailTemplates[currentEmailIndex];
  const totalEmails = emailTemplates.length;

  // Get validation results for current template
  const validationResults = validateEmail(currentTemplate?.template || { body: '' });

  // Auto-generate emails on component mount
  useEffect(() => {
    if (!hasAutoGenerated && selectedMembers.length > 0 && articleData.title) {
      setHasAutoGenerated(true);
      generateAIEmails();
    }
  }, []);

  const updateTemplate = (field, value) => {
    setEmailTemplates((prev) =>
      prev.map((template, index) =>
        index === currentEmailIndex
          ? {
              ...template,
              template: { ...template.template, [field]: value },
              isEdited: true,
            }
          : template
      )
    );
  };

  const updateContactInfo = (field, value) => {
    setEmailTemplates((prev) =>
      prev.map((template, index) =>
        index === currentEmailIndex
          ? {
              ...template,
              [field]: value,
              isEdited: true,
            }
          : template
      )
    );
  };

  const generateAIEmails = async () => {
    setIsGenerating(true);

    toast.info("Generating personalised emails...", {
      description: "This may take a few moments",
      duration: 2000,
    });

    try {
      const formattedMembers = selectedMembers.map((member) => ({
        id: member.id,
        name: member.company,
        company: member.company,
        role: "Industry Expert",
        expertise: member.expertise || [],
        bio: member.bio || "",
        marketSegments: member.marketSegments || [],
        geographicFocus: member.geographicFocus || [],
      }));

      const response = await fetch("/api/generate-emails", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          articleData,
          selectedMembers: formattedMembers,
        }),
      });

      const data = await response.json();

      if (data.success) {
        setEmailTemplates((prev) =>
          prev.map((template) => {
            const aiTemplate = data.emails.find(
              (email) => email.memberId === template.companyId
            );
            if (aiTemplate) {
              return {
                ...template,
                template: aiTemplate.template,
                isEdited: true,
              };
            }
            return template;
          })
        );
        toast.success("AI-generated emails created!", {
          description: `Generated ${data.emails.length} personalised templates`,
          duration: 3000,
        });
      } else {
        toast.error("Failed to generate AI emails", {
          description: "Using default templates instead",
        });
      }
    } catch (error) {
      console.error("Email generation error:", error);
      toast.error("Error generating emails", {
        description: "Using default templates instead",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const copyToClipboard = async (text, fieldName) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedField(fieldName);
      toast.success(`${fieldName} copied to clipboard`);
      setTimeout(() => setCopiedField(null), 2000);
    } catch (err) {
      toast.error("Failed to copy to clipboard");
    }
  };

  const handleApproveEmail = () => {
    // Check for critical validation issues
    if (validationResults.issues.length > 0) {
      toast.error("Cannot approve email with validation errors", {
        description: "Please fix all critical issues first",
        duration: 4000,
      });
      return;
    }

    setEmailTemplates((prev) =>
      prev.map((template, index) =>
        index === currentEmailIndex
          ? { ...template, isApproved: true }
          : template
      )
    );

    if (currentEmailIndex < totalEmails - 1) {
      setCurrentEmailIndex(currentEmailIndex + 1);
      toast.success("Email approved! Moving to next...");
    } else {
      toast.success("All emails reviewed!", {
        description: "Ready to proceed to final step",
        duration: 3000,
      });
    }
  };

  const handlePrevious = () => {
    if (currentEmailIndex > 0) {
      setCurrentEmailIndex(currentEmailIndex - 1);
    }
  };

  const handleNext = () => {
    if (currentEmailIndex < totalEmails - 1) {
      setCurrentEmailIndex(currentEmailIndex + 1);
    }
  };

  const handleContinue = () => {
    const unapprovedEmails = emailTemplates.filter(
      (template) => !template.isApproved
    );

    if (unapprovedEmails.length > 0) {
      toast.error(
        `Please review and approve all emails (${unapprovedEmails.length} remaining)`
      );
      return;
    }

    toast.success("All emails approved!", {
      description: `Ready to send ${emailTemplates.length} personalised messages`,
      duration: 3000,
    });

    onContinue?.(emailTemplates);
  };

  const handleBack = () => {
    onBack?.();
  };

  const approvedCount = emailTemplates.filter(
    (template) => template.isApproved
  ).length;

  if (!currentTemplate) return null;

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-teal-50/30 to-emerald-100/20 dark:from-slate-900 dark:via-teal-950/30 dark:to-emerald-950/20 p-6 transition-colors duration-300">
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#8882_1px,transparent_1px),linear-gradient(to_bottom,#8882_1px,transparent_1px)] bg-[size:24px_24px] pointer-events-none"></div>

      {/* Theme Toggle - Fixed Position */}
      <div className="fixed top-6 right-6 z-50">
        <ThemeToggle />
      </div>

      {/* Loading Overlay */}
      {isGenerating && (
        <div className="fixed inset-0 z-50 bg-black/20 backdrop-blur-sm flex items-center justify-center">
          <div className="bg-white dark:bg-slate-800 rounded-2xl p-8 shadow-2xl max-w-md mx-4">
            <div className="flex flex-col items-center gap-4">
              <Loader2 className="w-12 h-12 text-[#00DFB8] animate-spin" />
              <div className="text-center">
                <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-2">
                  Generating personalised emails...
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  Our AI is crafting {selectedMembers.length} custom emails
                  based on company expertise
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      <div className="relative max-w-7xl mx-auto">
        <div className="backdrop-blur-xl bg-white/70 dark:bg-slate-800/70 border border-white/20 dark:border-slate-700/20 rounded-3xl shadow-2xl shadow-teal-500/10 overflow-hidden transition-colors duration-300">
          <div className="bg-gradient-to-r from-white/80 via-white/60 to-white/80 dark:from-slate-800/80 dark:via-slate-800/60 dark:to-slate-800/80 backdrop-blur-sm border-b border-white/20 dark:border-slate-700/20 p-8 transition-colors duration-300">
            <TPAMailLogo />

            {articleData.title && (
              <div className="mb-4 p-3 bg-white/30 dark:bg-slate-700/30 backdrop-blur-sm border border-white/20 dark:border-slate-600/20 rounded-lg">
                <div className="flex items-center gap-2 mb-2">
                  <FileText className="w-4 h-4 text-[#00DFB8]" />
                  <span className="text-sm font-medium text-gray-700 dark:text-gray-200">
                    Article: "{articleData.title}"
                  </span>
                </div>
              </div>
            )}

            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-xl font-semibold text-gray-800 dark:text-gray-200 mb-2">
                  Review email templates
                </h2>
                <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                  AI-generated personalised emails are ready. Review and
                  customise each template, then add contact details.
                </p>
              </div>
              <div className="text-right">
                <div className="text-2xl font-bold text-[#00DFB8]">
                  {approvedCount}/{totalEmails}
                </div>
                <div className="text-sm text-gray-500 dark:text-gray-400">approved</div>
              </div>
            </div>
          </div>

          <div className="p-8">
            {/* Progress Bar */}
            <div className="mb-8">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm font-medium text-gray-700 dark:text-gray-200">
                  Email {currentEmailIndex + 1} of {totalEmails}
                </span>
                <div className="flex gap-2">
                  <span className="text-sm text-gray-500 dark:text-gray-400">
                    {Math.round((approvedCount / totalEmails) * 100)}% complete
                  </span>
                </div>
              </div>
              <div className="w-full bg-white/40 dark:bg-slate-700/40 rounded-full h-2 backdrop-blur-sm">
                <div
                  className="bg-gradient-to-r from-[#00DFB8] to-[#00B894] h-2 rounded-full transition-all duration-300"
                  style={{ width: `${(approvedCount / totalEmails) * 100}%` }}
                ></div>
              </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
              {/* Company Info Sidebar */}
              <div className="lg:col-span-1">
                <Card className="bg-white/50 dark:bg-slate-700/50 backdrop-blur-sm border-white/30 dark:border-slate-600/30 sticky top-8 transition-colors duration-300">
                  <CardHeader className="pb-4">
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-12 h-12 bg-gradient-to-br from-[#00DFB8] to-[#00B894] rounded-xl flex items-center justify-center text-white font-semibold">
                        {currentTemplate.company.company
                          .substring(0, 2)
                          .toUpperCase()}
                      </div>
                      <div>
                        <CardTitle className="text-lg dark:text-gray-200">
                          {currentTemplate.company.company}
                        </CardTitle>
                        <CardDescription className="text-sm dark:text-gray-400">
                          {currentTemplate.company.employeeCount} employees
                        </CardDescription>
                      </div>
                    </div>

                    <div className="space-y-3 mb-4">
                      <h4 className="text-sm font-semibold text-gray-700 dark:text-gray-200">
                        Expertise areas
                      </h4>
                      <div className="flex flex-wrap gap-1">
                        {currentTemplate.company.expertise.map(
                          (skill, index) => (
                            <Badge
                              key={index}
                              variant="outline"
                              className="text-xs bg-white/50 dark:bg-slate-600/50 border-[#00DFB8]/20 text-gray-600 dark:text-gray-300"
                            >
                              {skill}
                            </Badge>
                          )
                        )}
                      </div>
                    </div>

                    {/* Status Badge */}
                    <div className="pt-4 border-t border-white/20 dark:border-slate-600/20">
                      {currentTemplate.isApproved ? (
                        <Badge className="bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-400 border-green-200 dark:border-green-800">
                          <Check className="w-3 h-3 mr-1" />
                          Approved
                        </Badge>
                      ) : (
                        <Badge
                          variant="outline"
                          className="bg-yellow-50 dark:bg-yellow-900/20 text-yellow-800 dark:text-yellow-400 border-yellow-200 dark:border-yellow-800"
                        >
                          Pending review
                        </Badge>
                      )}
                    </div>
                  </CardHeader>
                </Card>
              </div>

              {/* Email Template Editor */}
              <div className="lg:col-span-2 space-y-6">
                {/* Navigation */}
                <div className="flex items-center justify-between">
                  <Button
                    variant="outline"
                    onClick={handlePrevious}
                    disabled={currentEmailIndex === 0}
                    className="bg-white/50 dark:bg-slate-700/50 backdrop-blur-sm border-white/30 dark:border-slate-600/30 hover:bg-white/70 dark:hover:bg-slate-700/70"
                  >
                    <ChevronLeft className="w-4 h-4 mr-1" />
                    Previous
                  </Button>

                  <div className="flex gap-1">
                    {emailTemplates.map((_, index) => (
                      <button
                        key={index}
                        onClick={() => setCurrentEmailIndex(index)}
                        className={`w-3 h-3 rounded-full transition-all ${
                          index === currentEmailIndex
                            ? "bg-[#00DFB8]"
                            : emailTemplates[index].isApproved
                            ? "bg-green-400"
                            : "bg-gray-300 dark:bg-gray-600"
                        }`}
                      />
                    ))}
                  </div>

                  <Button
                    variant="outline"
                    onClick={handleNext}
                    disabled={currentEmailIndex === totalEmails - 1}
                    className="bg-white/50 dark:bg-slate-700/50 backdrop-blur-sm border-white/30 dark:border-slate-600/30 hover:bg-white/70 dark:hover:bg-slate-700/70"
                  >
                    Next
                    <ChevronRight className="w-4 h-4 ml-1" />
                  </Button>
                </div>

                {/* Validation Warnings */}
                {(validationResults.issues.length > 0 || validationResults.warnings.length > 0) && (
                  <div className={`rounded-lg p-4 border ${
                    validationResults.issues.length > 0 
                      ? 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800' 
                      : 'bg-yellow-50 dark:bg-yellow-900/20 border-yellow-200 dark:border-yellow-800'
                  }`}>
                    <h4 className={`text-sm font-semibold mb-2 flex items-center gap-2 ${
                      validationResults.issues.length > 0 
                        ? 'text-red-800 dark:text-red-400' 
                        : 'text-yellow-800 dark:text-yellow-400'
                    }`}>
                      <AlertTriangle className="w-4 h-4" />
                      {validationResults.issues.length > 0 ? 'Critical issues' : 'Warnings'}
                    </h4>
                    
                    {validationResults.issues.length > 0 && (
                      <ul className="text-sm text-red-700 dark:text-red-400 space-y-1 mb-2">
                        {validationResults.issues.map((issue, idx) => (
                          <li key={idx}>• {issue}</li>
                        ))}
                      </ul>
                    )}
                    
                    {validationResults.warnings.length > 0 && (
                      <ul className="text-sm text-yellow-700 dark:text-yellow-400 space-y-1">
                        {validationResults.warnings.map((warning, idx) => (
                          <li key={idx}>• {warning}</li>
                        ))}
                      </ul>
                    )}
                  </div>
                )}

                {/* Subject Line */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <label className="text-sm font-semibold text-gray-700 dark:text-gray-200">
                      Subject line
                    </label>
                    <div className="flex gap-2">
                      {currentTemplate.isEdited && (
                        <Badge
                          variant="outline"
                          className="text-xs bg-[#00DFB8]/10 border-[#00DFB8]/20 text-[#00DFB8]"
                        >
                          <Edit3 className="w-3 h-3 mr-1" />
                          Edited
                        </Badge>
                      )}
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() =>
                          copyToClipboard(
                            currentTemplate.template.subject,
                            "Subject"
                          )
                        }
                        className="h-7 px-2"
                      >
                        {copiedField === "Subject" ? (
                          <Check className="w-3 h-3" />
                        ) : (
                          <Copy className="w-3 h-3" />
                        )}
                      </Button>
                    </div>
                  </div>
                  <input
                    type="text"
                    value={currentTemplate.template.subject}
                    onChange={(e) => updateTemplate("subject", e.target.value)}
                    className="w-full px-4 py-3 text-base bg-white/50 dark:bg-slate-700/50 backdrop-blur-sm border border-white/30 dark:border-slate-600/30 rounded-xl shadow-sm hover:bg-white/70 dark:hover:bg-slate-700/70 focus:bg-white/80 dark:focus:bg-slate-700/80 focus:border-[#00DFB8]/30 transition-all duration-300 placeholder:text-gray-400 dark:placeholder:text-gray-500"
                    placeholder="Enter email subject..."
                  />
                </div>

                {/* Email Body */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <label className="text-sm font-semibold text-gray-700 dark:text-gray-200">
                      Email content
                    </label>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() =>
                        copyToClipboard(
                          currentTemplate.template.body,
                          "Email content"
                        )
                      }
                      className="h-7 px-2"
                    >
                      {copiedField === "Email content" ? (
                        <Check className="w-3 h-3" />
                      ) : (
                        <Copy className="w-3 h-3" />
                      )}
                    </Button>
                  </div>
                  <div className="relative">
                    <Textarea
                      value={currentTemplate.template.body}
                      onChange={(e) => updateTemplate("body", e.target.value)}
                      className="min-h-[400px] text-base bg-white/50 dark:bg-slate-700/50 backdrop-blur-sm border border-white/30 dark:border-slate-600/30 rounded-xl shadow-sm hover:bg-white/70 dark:hover:bg-slate-700/70 focus:bg-white/80 dark:focus:bg-slate-700/80 focus:border-[#00DFB8]/30 transition-all duration-300 placeholder:text-gray-400 dark:placeholder:text-gray-500 resize-none"
                      placeholder="Enter email content..."
                      rows={16}
                    />
                    <div className="absolute bottom-4 right-4">
                      <Badge
                        variant="outline"
                        className="bg-white/70 dark:bg-slate-600/70 border-gray-200 dark:border-slate-500"
                      >
                        {
                          (currentTemplate?.template?.body || "")
                            .split(" ")
                            .filter((w) => w.length > 0).length
                        }{" "}
                        words
                      </Badge>
                    </div>
                  </div>
                </div>

                {/* Fields to Fill Warning */}
                <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
                  <h4 className="text-sm font-semibold text-blue-800 dark:text-blue-400 mb-2">
                    📝 Remember to update:
                  </h4>
                  <ul className="text-sm text-blue-700 dark:text-blue-400 space-y-1">
                    <li>• Specific contact name and role</li>
                    <li>• Any deadline dates marked with **XXX**</li>
                  </ul>
                </div>

                {/* Approve Button */}
                <div className="flex justify-end">
                  {currentTemplate.isApproved ? (
                    <Badge className="bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-400 border-green-200 dark:border-green-800 px-4 py-2">
                      <Check className="w-4 h-4 mr-2" />
                      Email approved
                    </Badge>
                  ) : (
                    <Button
                      onClick={handleApproveEmail}
                      disabled={validationResults.issues.length > 0}
                      className="px-6 py-3 bg-gradient-to-r from-[#00DFB8] to-[#00B894] hover:from-[#00B894] hover:to-[#00A085] text-white border-0 rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      <Check className="w-4 h-4 mr-2" />
                      Approve & continue
                    </Button>
                  )}
                </div>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex justify-between items-center pt-8 mt-8 border-t border-white/20 dark:border-slate-700/20">
              <Button
                variant="outline"
                onClick={handleBack}
                className="px-6 bg-white/50 dark:bg-slate-700/50 backdrop-blur-sm border-white/30 dark:border-slate-600/30 hover:bg-white/70 dark:hover:bg-slate-700/70"
              >
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to companies
              </Button>

              <Button
                size="lg"
                onClick={() => window.location.reload()}
                className="px-8 py-3 bg-gradient-to-r from-[#00DFB8] via-[#00B894] to-[#00A085] hover:from-[#00B894] hover:via-[#00A085] hover:to-[#008B73] text-white border-0 rounded-xl shadow-lg hover:shadow-2xl transition-all duration-300 group"
              >
                <span className="flex items-center gap-2">
                  <svg
                    className="w-4 h-4"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
                    />
                  </svg>
                  Restart
                  <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </span>
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}