[
  {
    id: 1,
    company: "ACI Worldwide",
    expertise: ["Payment Orchestration", "Real-time Payments", "Fraud Management"],
    interests: ["AI-driven routing", "Cross-border optimization", "Authorization rate improvement"],
    avatar: "ACI",
    bio: "Original innovator in global payments technology, delivers transformative software solutions that power intelligent payments orchestration in real time",
    marketSegments: ["Enterprise", "Banks", "Merchants", "PSPs"],
    geographicFocus: ["Global", "UK", "EU", "APAC"],
    solutionTypes: ["Technology Platform", "Software Solutions", "Managed Services"],
    deliveryModels: ["Cloud", "On-premise", "Hybrid", "SaaS"],
    employeeCount: "1000+",
    recentInitiatives: ["Best-in-class payments orchestration (Datos 2024)", "AI/ML fraud prevention", "Real-time payment network support"],
    partnershipEcosystem: ["Visa", "Mastercard", "Global payment schemes", "Cloud providers"],
    regulatoryExpertise: ["PSD2", "Open Banking", "Real-time payment regulations", "AML compliance"],
    industryRecognition: ["Best in Class Merchant Payments Orchestration", "Leader in IDC MarketScape Worldwide Integrated Bank Payment Systems"]
  },
  {
    id: 2,
    company: "Addleshaw Goddard",
    expertise: ["Regulatory Compliance", "Financial Services Law", "ESG Advisory"],
    interests: ["Consumer duty implementation", "Sustainable finance regulation", "Digital asset frameworks"],
    avatar: "AG",
    bio: "Leading UK law firm with one of the strongest and most compelling payments offerings in the UK and Europe",
    marketSegments: ["Banks", "Building Societies", "Payment Institutions", "Fintechs"],
    geographicFocus: ["UK", "EU", "Global"],
    solutionTypes: ["Legal Advisory", "Regulatory Consulting", "Transaction Support"],
    deliveryModels: ["Professional Services", "Retainer Agreements", "Project-based"],
    employeeCount: "1000+",
    recentInitiatives: ["Consumer Duty implementation", "ESG regulatory frameworks", "Digital currency legal guidance"],
    partnershipEcosystem: ["Financial services regulators", "Industry associations", "Professional networks"],
    regulatoryExpertise: ["FSMA", "PRA and FCA rules", "ESG regulations", "CBDC frameworks", "AML/CTF"],
    industryRecognition: ["Unmatched depth and quality of advice", "Leading payments law practice", "ESG legal expertise"]
  },
  {
    id: 3,
    company: "AuthoriPay Ltd",
    expertise: ["Regulatory Licensing", "Financial Crime Prevention", "Fintech Enablement"],
    interests: ["APP fraud mitigation", "Financial inclusion licensing", "Emerging payment regulations"],
    avatar: "AP",
    bio: "Pioneering regulatory consultancy with a focus on payment and e-money institutions, committed to upholding the highest standards of integrity",
    marketSegments: ["Fintechs", "Payment Institutions", "E-money Firms", "Emerging markets"],
    geographicFocus: ["UK", "EEA", "Emerging markets"],
    solutionTypes: ["Regulatory Consulting", "Licensing Support", "Compliance Audits"],
    deliveryModels: ["Consulting Services", "Agent Programmes", "Managed Compliance"],
    employeeCount: "50-200",
    recentInitiatives: ["APP fraud reimbursement rules guidance", "Financial inclusion licensing support", "Cryptocurrency compliance frameworks"],
    partnershipEcosystem: ["FCA", "Card schemes", "Banking partners", "Fintech accelerators"],
    regulatoryExpertise: ["Payment Services Regulations", "Electronic Money Regulations", "APP fraud rules", "Financial inclusion policies"],
    industryRecognition: ["Association of Professional Compliance Consultants members", "Industry regulatory expertise", "Fintech community recognition"]
  },
  {
    id: 4,
    company: "BPC",
    expertise: ["Payment Processing", "Financial Inclusion", "Digital Banking"],
    interests: ["Agent banking solutions", "CBDC infrastructure", "Merchant acquiring platforms"],
    avatar: "BPC",
    bio: "Proven industry leader shaping the world of transactions with quick, safe and easy payment processing across 120 countries",
    marketSegments: ["Banks", "Microfinance", "Government", "Transport operators"],
    geographicFocus: ["Global", "Emerging markets", "EU", "APAC"],
    solutionTypes: ["Technology Platform", "White-label Solutions", "Processing Services"],
    deliveryModels: ["PaaS", "SaaS", "On-premise", "Managed Services"],
    employeeCount: "1000+",
    recentInitiatives: ["Oracle Cloud migration", "Financial inclusion marketplace", "Smart city payment platforms"],
    partnershipEcosystem: ["Oracle", "Visa", "Central banks", "Government agencies"],
    regulatoryExpertise: ["EMV compliance", "Financial inclusion regulations", "CBDC frameworks", "Cross-border payment rules"],
    industryRecognition: ["350+ customers globally", "27+ years payments expertise", "Financial inclusion innovation leader"]
  },
  {
    id: 5,
    company: "Capco",
    expertise: ["Digital Transformation", "ESG Strategy", "Financial Crime Consulting"],
    interests: ["GenAI implementation", "Sustainable finance solutions", "RegTech innovation"],
    avatar: "CAP",
    bio: "Global technology and management consultancy specializing in driving digital transformation in the financial services industry",
    marketSegments: ["Banks", "Capital Markets", "Insurance", "Wealth Management"],
    geographicFocus: ["Global", "UK", "EU", "Americas"],
    solutionTypes: ["Management Consulting", "Technology Implementation", "Digital Innovation"],
    deliveryModels: ["Consulting Services", "Innovation Labs", "Transformation Delivery"],
    employeeCount: "1000+",
    recentInitiatives: ["OpenAI collaboration", "ESG transformation programmes", "Digital currency advisory"],
    partnershipEcosystem: ["OpenAI", "Wipro", "Technology vendors", "Academic institutions"],
    regulatoryExpertise: ["Open Banking", "ESG reporting standards", "AML/KYC frameworks", "Digital asset regulations"],
    industryRecognition: ["Award-winning Be Yourself At Work culture", "100+ global organizations served", "ESG consulting excellence"]
  },

  {
    id: 6,
    company: "Cardaq Limited",
    expertise: ["Card Issuing", "Merchant Acquiring", "E-money Services"],
    interests: ["API integration", "White-label solutions", "Customised card programmes"],
    avatar: "CAR",
    bio: "FCA-authorised electronic money institution providing seamless payment processing and card issuing solutions for businesses worldwide",
    marketSegments: ["Merchants", "Financial Institutions", "Fintechs", "E-commerce"],
    geographicFocus: ["UK", "Canada", "EU"],
    solutionTypes: ["Payment Processing", "Card Issuing", "API Solutions"],
    deliveryModels: ["API-first", "White-label", "SaaS"],
    employeeCount: "50-200",
    recentInitiatives: ["Apple Pay and Google Pay integration", "Google Anti Money Laundering AI implementation", "Principal membership with Visa, Mastercard, UnionPay"],
    partnershipEcosystem: ["Visa", "Mastercard", "China UnionPay", "The Payments Association"],
    regulatoryExpertise: ["FCA regulations", "EMoney regulations", "AML compliance", "Card scheme compliance"],
    industryRecognition: ["Principal Members of Visa, Mastercard, and China UnionPay since 2019", "12+ years market experience"]
  },
  {
    id: 7,
    company: "Convera",
    expertise: ["Cross-border Payments", "FX Management", "Global Trade Finance"],
    interests: ["B2B international payments", "Real-time settlement", "Multi-currency solutions"],
    avatar: "CON",
    bio: "World's FX payments leader with USD 170B+ turnover in 2024 and over 40 years of foreign exchange expertise, making moving money simple, secure, and smart",
    marketSegments: ["Corporates", "SMEs", "Educational institutions", "Financial institutions"],
    geographicFocus: ["Global", "140+ currencies", "200+ countries"],
    solutionTypes: ["Payment Platform", "FX Services", "Risk Management"],
    deliveryModels: ["API", "Platform", "Managed Services"],
    employeeCount: "1000+",
    recentInitiatives: ["SWIFT gpi integration", "Real-time payment tracking", "Fintech 2025+ research report"],
    partnershipEcosystem: ["60+ global banking partners", "SWIFT", "Oxford Economics", "The Paypers"],
    regulatoryExpertise: ["60+ regulatory licences globally", "AML/KYC compliance", "Cross-border regulations", "SWIFT standards"],
    industryRecognition: ["Over 26,000 business clients", "USD 170B+ annual turnover", "40+ years FX expertise"]
  },
  {
    id: 8,
    company: "FIS",
    expertise: ["Core Banking", "Digital Banking", "Payment Processing"],
    interests: ["AI-driven solutions", "Cloud-native platforms", "Fintech innovation"],
    avatar: "FIS",
    bio: "Global leader in financial technology providing solutions that power the world's financial system with decades of experience helping institutions adapt and grow",
    marketSegments: ["Banks", "Credit unions", "Fintechs", "Capital markets"],
    geographicFocus: ["Global", "North America", "EU", "APAC"],
    solutionTypes: ["Technology Platform", "Software Solutions", "Managed Services"],
    deliveryModels: ["Cloud", "On-premise", "SaaS", "API"],
    employeeCount: "1000+",
    recentInitiatives: ["Amount acquisition (2024)", "Fintech Accelerator Program", "AI/ML integration", "FIS Automated Finance awards"],
    partnershipEcosystem: ["20,000+ clients", "1M+ merchant locations", "Technology vendors", "Fintech startups"],
    regulatoryExpertise: ["Banking regulations", "Capital markets compliance", "Payment regulations", "Data protection"],
    industryRecognition: ["Fortune 500 member", "S&P 500 Index", "$14.51B revenue (2024)", "Best Digital Solution Provider PayTech 2024"]
  },
  {
    id: 9,
    company: "Fiserv",
    expertise: ["Merchant Acquiring", "Payment Processing", "Financial Technology"],
    interests: ["Clover ecosystem", "Real-time payments", "Digital commerce solutions"],
    avatar: "FIV",
    bio: "Fortune 500 global leader in payments and financial technology helping clients achieve best-in-class results through innovation and excellence",
    marketSegments: ["Merchants", "Banks", "Credit unions", "ISVs"],
    geographicFocus: ["Global", "North America", "Latin America", "EU"],
    solutionTypes: ["Payment Processing", "POS Solutions", "Financial Technology"],
    deliveryModels: ["Cloud", "SaaS", "On-premise", "API"],
    employeeCount: "1000+",
    recentInitiatives: ["First MALPB charter (2024)", "Money Money acquisition (Brazil)", "Clover global expansion", "CCV acquisition"],
    partnershipEcosystem: ["2M+ ATMs (STAR network)", "Wells Fargo", "Walmart", "Global card schemes"],
    regulatoryExpertise: ["Payment regulations", "Banking compliance", "International regulations", "PCI compliance"],
    industryRecognition: ["Fortune 500 company", "$5.22B quarterly revenue", "First Merchant Acquirer Limited Purpose Bank", "Global Clover platform"]
  },
  {
    id: 10,
    company: "Latham & Watkins",
    expertise: ["Financial Regulation", "Payments Law", "Digital Assets Advisory"],
    interests: ["Crypto regulation", "Open banking law", "Fintech compliance"],
    avatar: "LW",
    bio: "Global law firm ranked Tier 1 in Fintech with significant strength in payments law, financial regulation, and cryptocurrency matters across major jurisdictions",
    marketSegments: ["Banks", "Fintechs", "Investment funds", "Crypto companies"],
    geographicFocus: ["Global", "US", "UK", "EU", "Asia"],
    solutionTypes: ["Legal Advisory", "Regulatory Consulting", "Transaction Support"],
    deliveryModels: ["Professional Services", "Regulatory guidance", "Transaction support"],
    employeeCount: "1000+",
    recentInitiatives: ["US Crypto Policy Tracker", "Digital Assets & Web3 practice", "Financial regulatory resources", "Fintech accelerator partnerships"],
    partnershipEcosystem: ["Regulatory bodies", "Industry associations", "a16z Crypto", "Technology companies"],
    regulatoryExpertise: ["SEC/CFTC regulations", "FCA rules", "PSD2/PSD3", "Digital asset frameworks", "AML/KYC"],
    industryRecognition: ["Only firm ranked Tier 1 Fintech on both sides of Atlantic", "Best global FinTech practice", "90 Band 1 practice rankings"]
  },
  {
    id: 11,
    company: "Lloyds Banking Group",
    expertise: ["Retail Banking", "Digital Banking", "SME Payments"],
    interests: ["Open banking innovation", "Digital transformation", "Financial inclusion"],
    avatar: "LBG",
    bio: "UK's largest digital bank serving over 26 million customers with market-leading positions in retail banking, mortgages, and commercial banking",
    marketSegments: ["Retail customers", "SMEs", "Commercial banking", "Private banking"],
    geographicFocus: ["UK", "EU"],
    solutionTypes: ["Banking Services", "Payment Solutions", "Digital Platforms"],
    deliveryModels: ["Digital-first", "Branch network", "API banking"],
    employeeCount: "1000+",
    recentInitiatives: ["Digital transformation programme", "Open banking API expansion", "ESG financing commitments", "Financial inclusion initiatives"],
    partnershipEcosystem: ["Fintech partners", "Government initiatives", "Industry associations", "Payment schemes"],
    regulatoryExpertise: ["UK banking regulations", "Open Banking Standards", "Consumer Duty", "ESG compliance"],
    industryRecognition: ["UK's largest digital bank", "26M+ customers", "Market leader in UK retail banking"]
  },
  {
    id: 12,
    company: "Mastercard",
    expertise: ["Payment Networks", "Digital Payments", "Data Analytics"],
    interests: ["Real-time payments", "Digital identity", "Crypto integration"],
    avatar: "MC",
    bio: "Global payment technology company connecting consumers, financial institutions, merchants, governments across 210+ countries and territories",
    marketSegments: ["Banks", "Merchants", "Governments", "Fintechs"],
    geographicFocus: ["Global", "210+ countries", "EU", "UK"],
    solutionTypes: ["Payment Network", "Technology Solutions", "Data Services"],
    deliveryModels: ["Network services", "API platform", "SaaS solutions"],
    employeeCount: "1000+",
    recentInitiatives: ["Central bank digital currency partnerships", "Open banking solutions", "ESG payment solutions", "AI-powered fraud detection"],
    partnershipEcosystem: ["25,000+ financial institutions", "Central banks", "Governments", "Fintech ecosystem"],
    regulatoryExpertise: ["Global payment regulations", "CBDC frameworks", "Open banking standards", "AML compliance"],
    industryRecognition: ["Global payment network leader", "210+ countries coverage", "Multi-billion transaction processing"]
  },
  {
    id: 13,
    company: "Nationwide",
    expertise: ["Building Society Services", "Digital Banking", "Member-focused Banking"],
    interests: ["Open banking services", "ESG initiatives", "Financial wellbeing"],
    avatar: "NW",
    bio: "UK's largest building society with over 16 million members, putting member interests first with innovative digital banking and mortgage services",
    marketSegments: ["Retail members", "SMEs", "First-time buyers", "Savers"],
    geographicFocus: ["UK"],
    solutionTypes: ["Banking Services", "Mortgage Services", "Digital Solutions"],
    deliveryModels: ["Digital-first", "Branch network", "Member services"],
    employeeCount: "1000+",
    recentInitiatives: ["Digital transformation", "Open banking implementation", "ESG commitments", "Financial inclusion programmes"],
    partnershipEcosystem: ["Building society movement", "Fintech partners", "Government schemes", "Community organisations"],
    regulatoryExpertise: ["Building Societies Act", "FCA regulations", "Open Banking Standards", "Consumer Duty"],
    industryRecognition: ["UK's largest building society", "16M+ members", "Mutual organisation focus"]
  },
  {
    id: 14,
    company: "NatWest",
    expertise: ["Commercial Banking", "Digital Innovation", "Open Banking"],
    interests: ["API development", "Fintech partnerships", "Business banking"],
    avatar: "RBS",
    bio: "Leading UK bank driving digital innovation with market-leading open banking platform and comprehensive business banking solutions",
    marketSegments: ["SMEs", "Corporates", "Retail customers", "Institutions"],
    geographicFocus: ["UK", "Ireland"],
    solutionTypes: ["Banking Services", "API Platform", "Digital Solutions"],
    deliveryModels: ["Digital banking", "API-first", "Branch network"],
    employeeCount: "1000+",
    recentInitiatives: ["Mettle business banking launch", "Open banking API expansion", "Climate commitments", "Innovation partnerships"],
    partnershipEcosystem: ["Fintech accelerators", "API marketplace", "Government partnerships", "Industry bodies"],
    regulatoryExpertise: ["UK banking regulations", "Open Banking Standards", "PSD2 compliance", "Climate risk frameworks"],
    industryRecognition: ["Leading open banking platform", "Award-winning business banking", "Major UK commercial bank"]
  },
  {
    id: 15,
    company: "Ocorian",
    expertise: ["Corporate Services", "Fund Administration", "Digital Assets"],
    interests: ["Crypto custody", "ESG compliance", "Digital transformation"],
    avatar: "OCO",
    bio: "Global leader in corporate and fiduciary services, fund solutions, and capital markets, with growing expertise in digital assets and sustainable finance",
    marketSegments: ["Asset managers", "Corporates", "Private equity", "Crypto firms"],
    geographicFocus: ["Global", "UK", "EU", "Asia", "Americas"],
    solutionTypes: ["Professional Services", "Technology Solutions", "Compliance Services"],
    deliveryModels: ["Professional services", "Technology platforms", "Managed services"],
    employeeCount: "1000+",
    recentInitiatives: ["Digital assets services expansion", "ESG reporting solutions", "Technology platform investments", "Regulatory compliance frameworks"],
    partnershipEcosystem: ["Financial institutions", "Law firms", "Technology providers", "Regulatory bodies"],
    regulatoryExpertise: ["International compliance", "Fund regulations", "Digital asset regulations", "ESG frameworks"],
    industryRecognition: ["Global corporate services leader", "Multi-jurisdictional expertise", "Digital assets innovation"]
  },
  {
    id: 16,
    company: "PagoNxt",
    expertise: ["Payment Processing", "Cross-border Payments", "Merchant Solutions"],
    interests: ["A2A payments", "Instant payments", "Global payment infrastructure"],
    avatar: "PNX",
    bio: "Santander's autonomous fintech delivering world-leading payment solutions, processing over 1 billion A2A transactions annually with cutting-edge cloud-native technology",
    marketSegments: ["Merchants", "SMEs", "Corporates", "Financial institutions"],
    geographicFocus: ["Global", "Europe", "Latin America", "North America"],
    solutionTypes: ["Payment Platform", "Merchant Acquiring", "Cross-border Solutions"],
    deliveryModels: ["Cloud-native SaaS", "API-first", "White-label"],
    employeeCount: "1000+",
    recentInitiatives: ["The Banker Innovation Award 2024", "Fedwire connection", "2 billion transactions target", "SEPA Instant compliance"],
    partnershipEcosystem: ["Santander Group", "Payment schemes", "Fintechs", "The Payments Association"],
    regulatoryExpertise: ["SEPA regulations", "Faster Payments", "PSD2 compliance", "Global payment regulations"],
    industryRecognition: ["1B+ annual transactions", "The Banker Innovation Award 2024", "160 years Santander heritage", "11 countries presence"]
  }
]
