export const membersDatabase = [
  {
    id: 1,
    company: "ACI Worldwide",
    expertise: ["Payment Orchestration", "Real-time Payments", "Fraud Management"],
    interests: ["AI-driven routing", "Cross-border optimization", "Authorization rate improvement"],
    avatar: "ACI",
    bio: "Original innovator in global payments technology, delivers transformative software solutions that power intelligent payments orchestration in real time",
    marketSegments: ["Enterprise", "Banks", "Merchants", "PSPs"],
    geographicFocus: ["Global", "UK", "EU", "APAC"],
    solutionTypes: ["Technology Platform", "Software Solutions", "Managed Services"],
    deliveryModels: ["Cloud", "On-premise", "Hybrid", "SaaS"],
    employeeCount: "1000+",
    recentInitiatives: ["Best-in-class payments orchestration (Datos 2024)", "AI/ML fraud prevention", "Real-time payment network support"],
    partnershipEcosystem: ["Visa", "Mastercard", "Global payment schemes", "Cloud providers"],
    regulatoryExpertise: ["PSD2", "Open Banking", "Real-time payment regulations", "AML compliance"],
    industryRecognition: ["Best in Class Merchant Payments Orchestration", "Leader in IDC MarketScape Worldwide Integrated Bank Payment Systems"]
  },
  {
    id: 2,
    company: "Addleshaw Goddard",
    expertise: ["Regulatory Compliance", "Financial Services Law", "ESG Advisory"],
    interests: ["Consumer duty implementation", "Sustainable finance regulation", "Digital asset frameworks"],
    avatar: "AG",
    bio: "Leading UK law firm with one of the strongest and most compelling payments offerings in the UK and Europe",
    marketSegments: ["Banks", "Building Societies", "Payment Institutions", "Fintechs"],
    geographicFocus: ["UK", "EU", "Global"],
    solutionTypes: ["Legal Advisory", "Regulatory Consulting", "Transaction Support"],
    deliveryModels: ["Professional Services", "Retainer Agreements", "Project-based"],
    employeeCount: "1000+",
    recentInitiatives: ["Consumer Duty implementation", "ESG regulatory frameworks", "Digital currency legal guidance"],
    partnershipEcosystem: ["Financial services regulators", "Industry associations", "Professional networks"],
    regulatoryExpertise: ["FSMA", "PRA and FCA rules", "ESG regulations", "CBDC frameworks", "AML/CTF"],
    industryRecognition: ["Unmatched depth and quality of advice", "Leading payments law practice", "ESG legal expertise"]
  },
  {
    id: 3,
    company: "AuthoriPay Ltd",
    expertise: ["Regulatory Licensing", "Financial Crime Prevention", "Fintech Enablement"],
    interests: ["APP fraud mitigation", "Financial inclusion licensing", "Emerging payment regulations"],
    avatar: "AP",
    bio: "Pioneering regulatory consultancy with a focus on payment and e-money institutions, committed to upholding the highest standards of integrity",
    marketSegments: ["Fintechs", "Payment Institutions", "E-money Firms", "Emerging markets"],
    geographicFocus: ["UK", "EEA", "Emerging markets"],
    solutionTypes: ["Regulatory Consulting", "Licensing Support", "Compliance Audits"],
    deliveryModels: ["Consulting Services", "Agent Programmes", "Managed Compliance"],
    employeeCount: "50-200",
    recentInitiatives: ["APP fraud reimbursement rules guidance", "Financial inclusion licensing support", "Cryptocurrency compliance frameworks"],
    partnershipEcosystem: ["FCA", "Card schemes", "Banking partners", "Fintech accelerators"],
    regulatoryExpertise: ["Payment Services Regulations", "Electronic Money Regulations", "APP fraud rules", "Financial inclusion policies"],
    industryRecognition: ["Association of Professional Compliance Consultants members", "Industry regulatory expertise", "Fintech community recognition"]
  },
  {
    id: 4,
    company: "BPC",
    expertise: ["Payment Processing", "Financial Inclusion", "Digital Banking"],
    interests: ["Agent banking solutions", "CBDC infrastructure", "Merchant acquiring platforms"],
    avatar: "BPC",
    bio: "Proven industry leader shaping the world of transactions with quick, safe and easy payment processing across 120 countries",
    marketSegments: ["Banks", "Microfinance", "Government", "Transport operators"],
    geographicFocus: ["Global", "Emerging markets", "EU", "APAC"],
    solutionTypes: ["Technology Platform", "White-label Solutions", "Processing Services"],
    deliveryModels: ["PaaS", "SaaS", "On-premise", "Managed Services"],
    employeeCount: "1000+",
    recentInitiatives: ["Oracle Cloud migration", "Financial inclusion marketplace", "Smart city payment platforms"],
    partnershipEcosystem: ["Oracle", "Visa", "Central banks", "Government agencies"],
    regulatoryExpertise: ["EMV compliance", "Financial inclusion regulations", "CBDC frameworks", "Cross-border payment rules"],
    industryRecognition: ["350+ customers globally", "27+ years payments expertise", "Financial inclusion innovation leader"]
  },
  {
    id: 5,
    company: "Capco",
    expertise: ["Digital Transformation", "ESG Strategy", "Financial Crime Consulting"],
    interests: ["GenAI implementation", "Sustainable finance solutions", "RegTech innovation"],
    avatar: "CAP",
    bio: "Global technology and management consultancy specializing in driving digital transformation in the financial services industry",
    marketSegments: ["Banks", "Capital Markets", "Insurance", "Wealth Management"],
    geographicFocus: ["Global", "UK", "EU", "Americas"],
    solutionTypes: ["Management Consulting", "Technology Implementation", "Digital Innovation"],
    deliveryModels: ["Consulting Services", "Innovation Labs", "Transformation Delivery"],
    employeeCount: "1000+",
    recentInitiatives: ["OpenAI collaboration", "ESG transformation programmes", "Digital currency advisory"],
    partnershipEcosystem: ["OpenAI", "Wipro", "Technology vendors", "Academic institutions"],
    regulatoryExpertise: ["Open Banking", "ESG reporting standards", "AML/KYC frameworks", "Digital asset regulations"],
    industryRecognition: ["Award-winning Be Yourself At Work culture", "100+ global organizations served", "ESG consulting excellence"]
  },

  {
    id: 6,
    company: "Cardaq Limited",
    expertise: ["Card Issuing", "Merchant Acquiring", "E-money Services"],
    interests: ["API integration", "White-label solutions", "Customised card programmes"],
    avatar: "CAR",
    bio: "FCA-authorised electronic money institution providing seamless payment processing and card issuing solutions for businesses worldwide",
    marketSegments: ["Merchants", "Financial Institutions", "Fintechs", "E-commerce"],
    geographicFocus: ["UK", "Canada", "EU"],
    solutionTypes: ["Payment Processing", "Card Issuing", "API Solutions"],
    deliveryModels: ["API-first", "White-label", "SaaS"],
    employeeCount: "50-200",
    recentInitiatives: ["Apple Pay and Google Pay integration", "Google Anti Money Laundering AI implementation", "Principal membership with Visa, Mastercard, UnionPay"],
    partnershipEcosystem: ["Visa", "Mastercard", "China UnionPay", "The Payments Association"],
    regulatoryExpertise: ["FCA regulations", "EMoney regulations", "AML compliance", "Card scheme compliance"],
    industryRecognition: ["Principal Members of Visa, Mastercard, and China UnionPay since 2019", "12+ years market experience"]
  },
  {
    id: 7,
    company: "Convera",
    expertise: ["Cross-border Payments", "FX Management", "Global Trade Finance"],
    interests: ["B2B international payments", "Real-time settlement", "Multi-currency solutions"],
    avatar: "CON",
    bio: "World's FX payments leader with USD 170B+ turnover in 2024 and over 40 years of foreign exchange expertise, making moving money simple, secure, and smart",
    marketSegments: ["Corporates", "SMEs", "Educational institutions", "Financial institutions"],
    geographicFocus: ["Global", "140+ currencies", "200+ countries"],
    solutionTypes: ["Payment Platform", "FX Services", "Risk Management"],
    deliveryModels: ["API", "Platform", "Managed Services"],
    employeeCount: "1000+",
    recentInitiatives: ["SWIFT gpi integration", "Real-time payment tracking", "Fintech 2025+ research report"],
    partnershipEcosystem: ["60+ global banking partners", "SWIFT", "Oxford Economics", "The Paypers"],
    regulatoryExpertise: ["60+ regulatory licences globally", "AML/KYC compliance", "Cross-border regulations", "SWIFT standards"],
    industryRecognition: ["Over 26,000 business clients", "USD 170B+ annual turnover", "40+ years FX expertise"]
  },
  {
    id: 8,
    company: "FIS",
    expertise: ["Core Banking", "Digital Banking", "Payment Processing"],
    interests: ["AI-driven solutions", "Cloud-native platforms", "Fintech innovation"],
    avatar: "FIS",
    bio: "Global leader in financial technology providing solutions that power the world's financial system with decades of experience helping institutions adapt and grow",
    marketSegments: ["Banks", "Credit unions", "Fintechs", "Capital markets"],
    geographicFocus: ["Global", "North America", "EU", "APAC"],
    solutionTypes: ["Technology Platform", "Software Solutions", "Managed Services"],
    deliveryModels: ["Cloud", "On-premise", "SaaS", "API"],
    employeeCount: "1000+",
    recentInitiatives: ["Amount acquisition (2024)", "Fintech Accelerator Program", "AI/ML integration", "FIS Automated Finance awards"],
    partnershipEcosystem: ["20,000+ clients", "1M+ merchant locations", "Technology vendors", "Fintech startups"],
    regulatoryExpertise: ["Banking regulations", "Capital markets compliance", "Payment regulations", "Data protection"],
    industryRecognition: ["Fortune 500 member", "S&P 500 Index", "$14.51B revenue (2024)", "Best Digital Solution Provider PayTech 2024"]
  },
  {
    id: 9,
    company: "Fiserv",
    expertise: ["Merchant Acquiring", "Payment Processing", "Financial Technology"],
    interests: ["Clover ecosystem", "Real-time payments", "Digital commerce solutions"],
    avatar: "FIV",
    bio: "Fortune 500 global leader in payments and financial technology helping clients achieve best-in-class results through innovation and excellence",
    marketSegments: ["Merchants", "Banks", "Credit unions", "ISVs"],
    geographicFocus: ["Global", "North America", "Latin America", "EU"],
    solutionTypes: ["Payment Processing", "POS Solutions", "Financial Technology"],
    deliveryModels: ["Cloud", "SaaS", "On-premise", "API"],
    employeeCount: "1000+",
    recentInitiatives: ["First MALPB charter (2024)", "Money Money acquisition (Brazil)", "Clover global expansion", "CCV acquisition"],
    partnershipEcosystem: ["2M+ ATMs (STAR network)", "Wells Fargo", "Walmart", "Global card schemes"],
    regulatoryExpertise: ["Payment regulations", "Banking compliance", "International regulations", "PCI compliance"],
    industryRecognition: ["Fortune 500 company", "$5.22B quarterly revenue", "First Merchant Acquirer Limited Purpose Bank", "Global Clover platform"]
  },
  {
    id: 10,
    company: "Latham & Watkins",
    expertise: ["Financial Regulation", "Payments Law", "Digital Assets Advisory"],
    interests: ["Crypto regulation", "Open banking law", "Fintech compliance"],
    avatar: "LW",
    bio: "Global law firm ranked Tier 1 in Fintech with significant strength in payments law, financial regulation, and cryptocurrency matters across major jurisdictions",
    marketSegments: ["Banks", "Fintechs", "Investment funds", "Crypto companies"],
    geographicFocus: ["Global", "US", "UK", "EU", "Asia"],
    solutionTypes: ["Legal Advisory", "Regulatory Consulting", "Transaction Support"],
    deliveryModels: ["Professional Services", "Regulatory guidance", "Transaction support"],
    employeeCount: "1000+",
    recentInitiatives: ["US Crypto Policy Tracker", "Digital Assets & Web3 practice", "Financial regulatory resources", "Fintech accelerator partnerships"],
    partnershipEcosystem: ["Regulatory bodies", "Industry associations", "a16z Crypto", "Technology companies"],
    regulatoryExpertise: ["SEC/CFTC regulations", "FCA rules", "PSD2/PSD3", "Digital asset frameworks", "AML/KYC"],
    industryRecognition: ["Only firm ranked Tier 1 Fintech on both sides of Atlantic", "Best global FinTech practice", "90 Band 1 practice rankings"]
  },
  {
    id: 11,
    company: "Lloyds Banking Group",
    expertise: ["Retail Banking", "Digital Banking", "SME Payments"],
    interests: ["Open banking innovation", "Digital transformation", "Financial inclusion"],
    avatar: "LBG",
    bio: "UK's largest digital bank serving over 26 million customers with market-leading positions in retail banking, mortgages, and commercial banking",
    marketSegments: ["Retail customers", "SMEs", "Commercial banking", "Private banking"],
    geographicFocus: ["UK", "EU"],
    solutionTypes: ["Banking Services", "Payment Solutions", "Digital Platforms"],
    deliveryModels: ["Digital-first", "Branch network", "API banking"],
    employeeCount: "1000+",
    recentInitiatives: ["Digital transformation programme", "Open banking API expansion", "ESG financing commitments", "Financial inclusion initiatives"],
    partnershipEcosystem: ["Fintech partners", "Government initiatives", "Industry associations", "Payment schemes"],
    regulatoryExpertise: ["UK banking regulations", "Open Banking Standards", "Consumer Duty", "ESG compliance"],
    industryRecognition: ["UK's largest digital bank", "26M+ customers", "Market leader in UK retail banking"]
  },
  {
    id: 12,
    company: "Mastercard",
    expertise: ["Payment Networks", "Digital Payments", "Data Analytics"],
    interests: ["Real-time payments", "Digital identity", "Crypto integration"],
    avatar: "MC",
    bio: "Global payment technology company connecting consumers, financial institutions, merchants, governments across 210+ countries and territories",
    marketSegments: ["Banks", "Merchants", "Governments", "Fintechs"],
    geographicFocus: ["Global", "210+ countries", "EU", "UK"],
    solutionTypes: ["Payment Network", "Technology Solutions", "Data Services"],
    deliveryModels: ["Network services", "API platform", "SaaS solutions"],
    employeeCount: "1000+",
    recentInitiatives: ["Central bank digital currency partnerships", "Open banking solutions", "ESG payment solutions", "AI-powered fraud detection"],
    partnershipEcosystem: ["25,000+ financial institutions", "Central banks", "Governments", "Fintech ecosystem"],
    regulatoryExpertise: ["Global payment regulations", "CBDC frameworks", "Open banking standards", "AML compliance"],
    industryRecognition: ["Global payment network leader", "210+ countries coverage", "Multi-billion transaction processing"]
  },
  {
    id: 13,
    company: "Nationwide",
    expertise: ["Building Society Services", "Digital Banking", "Member-focused Banking"],
    interests: ["Open banking services", "ESG initiatives", "Financial wellbeing"],
    avatar: "NW",
    bio: "UK's largest building society with over 16 million members, putting member interests first with innovative digital banking and mortgage services",
    marketSegments: ["Retail members", "SMEs", "First-time buyers", "Savers"],
    geographicFocus: ["UK"],
    solutionTypes: ["Banking Services", "Mortgage Services", "Digital Solutions"],
    deliveryModels: ["Digital-first", "Branch network", "Member services"],
    employeeCount: "1000+",
    recentInitiatives: ["Digital transformation", "Open banking implementation", "ESG commitments", "Financial inclusion programmes"],
    partnershipEcosystem: ["Building society movement", "Fintech partners", "Government schemes", "Community organisations"],
    regulatoryExpertise: ["Building Societies Act", "FCA regulations", "Open Banking Standards", "Consumer Duty"],
    industryRecognition: ["UK's largest building society", "16M+ members", "Mutual organisation focus"]
  },
  {
    id: 14,
    company: "NatWest",
    expertise: ["Commercial Banking", "Digital Innovation", "Open Banking"],
    interests: ["API development", "Fintech partnerships", "Business banking"],
    avatar: "RBS",
    bio: "Leading UK bank driving digital innovation with market-leading open banking platform and comprehensive business banking solutions",
    marketSegments: ["SMEs", "Corporates", "Retail customers", "Institutions"],
    geographicFocus: ["UK", "Ireland"],
    solutionTypes: ["Banking Services", "API Platform", "Digital Solutions"],
    deliveryModels: ["Digital banking", "API-first", "Branch network"],
    employeeCount: "1000+",
    recentInitiatives: ["Mettle business banking launch", "Open banking API expansion", "Climate commitments", "Innovation partnerships"],
    partnershipEcosystem: ["Fintech accelerators", "API marketplace", "Government partnerships", "Industry bodies"],
    regulatoryExpertise: ["UK banking regulations", "Open Banking Standards", "PSD2 compliance", "Climate risk frameworks"],
    industryRecognition: ["Leading open banking platform", "Award-winning business banking", "Major UK commercial bank"]
  },
  {
    id: 15,
    company: "Ocorian",
    expertise: ["Corporate Services", "Fund Administration", "Digital Assets"],
    interests: ["Crypto custody", "ESG compliance", "Digital transformation"],
    avatar: "OCO",
    bio: "Global leader in corporate and fiduciary services, fund solutions, and capital markets, with growing expertise in digital assets and sustainable finance",
    marketSegments: ["Asset managers", "Corporates", "Private equity", "Crypto firms"],
    geographicFocus: ["Global", "UK", "EU", "Asia", "Americas"],
    solutionTypes: ["Professional Services", "Technology Solutions", "Compliance Services"],
    deliveryModels: ["Professional services", "Technology platforms", "Managed services"],
    employeeCount: "1000+",
    recentInitiatives: ["Digital assets services expansion", "ESG reporting solutions", "Technology platform investments", "Regulatory compliance frameworks"],
    partnershipEcosystem: ["Financial institutions", "Law firms", "Technology providers", "Regulatory bodies"],
    regulatoryExpertise: ["International compliance", "Fund regulations", "Digital asset regulations", "ESG frameworks"],
    industryRecognition: ["Global corporate services leader", "Multi-jurisdictional expertise", "Digital assets innovation"]
  },
  {
    id: 16,
    company: "PagoNxt",
    expertise: ["Payment Processing", "Cross-border Payments", "Merchant Solutions"],
    interests: ["A2A payments", "Instant payments", "Global payment infrastructure"],
    avatar: "PNX",
    bio: "Santander's autonomous fintech delivering world-leading payment solutions, processing over 1 billion A2A transactions annually with cutting-edge cloud-native technology",
    marketSegments: ["Merchants", "SMEs", "Corporates", "Financial institutions"],
    geographicFocus: ["Global", "Europe", "Latin America", "North America"],
    solutionTypes: ["Payment Platform", "Merchant Acquiring", "Cross-border Solutions"],
    deliveryModels: ["Cloud-native SaaS", "API-first", "White-label"],
    employeeCount: "1000+",
    recentInitiatives: ["The Banker Innovation Award 2024", "Fedwire connection", "2 billion transactions target", "SEPA Instant compliance"],
    partnershipEcosystem: ["Santander Group", "Payment schemes", "Fintechs", "The Payments Association"],
    regulatoryExpertise: ["SEPA regulations", "Faster Payments", "PSD2 compliance", "Global payment regulations"],
    industryRecognition: ["1B+ annual transactions", "The Banker Innovation Award 2024", "160 years Santander heritage", "11 countries presence"]
  },
  {
    id: 17,
    company: "Payall",
    expertise: ["Cross-border Payments", "Correspondent Banking", "Payment Infrastructure"],
    interests: ["Instant payments", "Compliance automation", "Financial inclusion"],
    avatar: "PAL",
    bio: "First-ever cross-border processor delivering correspondent banking-as-a-service with 24/7 instant cross-border payments, enabling banks to move money safely at the speed of data through breakthrough automated compliance",
    marketSegments: ["Banks", "EMIs", "Credit unions", "Payment channels"],
    geographicFocus: ["Global", "UK", "US", "Europe"],
    solutionTypes: ["Payment Processing", "Compliance Software", "Banking Infrastructure"],
    deliveryModels: ["Cloud-native platform", "API-first", "BPaaS"],
    employeeCount: "100-500",
    recentInitiatives: ["Know Your Customer's Customer product", "Precision KYT automation", "130 countries coverage", "Global consent management"],
    partnershipEcosystem: ["Mastercard", "The Payments Association", "Financial institutions", "Central banks"],
    regulatoryExpertise: ["Cross-border compliance", "KYC/KYT automation", "Sanctions screening", "Global payment regulations"],
    industryRecognition: ["First-ever cross-border processor", "Automated compliance pioneer", "90+ currencies support", "Real-time bank transfers"]
  },
  {
    id: 18,
    company: "Paymentology",
    expertise: ["Card Issuing", "Payment Processing", "Digital Payments"],
    interests: ["Cloud-native platforms", "Virtual cards", "Embedded finance"],
    avatar: "PYM",
    bio: "Next-generation cloud-native global issuer-processor enabling banks and fintechs to issue and process physical and virtual cards, operating in 50+ countries with 24/7 support across 14 time zones",
    marketSegments: ["Banks", "Fintechs", "Telcos", "Retailers"],
    geographicFocus: ["Global", "Europe", "Middle East", "Africa", "Asia Pacific"],
    solutionTypes: ["Card Issuing Platform", "Processing Services", "Programme Management"],
    deliveryModels: ["Cloud SaaS", "API-first", "Managed services"],
    employeeCount: "1000+",
    recentInitiatives: ["Merger of Tutuka and Paymentology UK", "Teya partnership", "Multi-currency capabilities", "Digital wallet integration"],
    partnershipEcosystem: ["Visa", "Mastercard", "UnionPay", "Mambu", "10x Banking"],
    regulatoryExpertise: ["PCI-DSS compliance", "Multi-jurisdictional licensing", "Card scheme regulations", "Digital payments frameworks"],
    industryRecognition: ["Leading global issuer-processor", "Cloud-native pioneer", "Technology leader CMS", "50+ countries presence"]
  },
  {
    id: 19,
    company: "Post Office",
    expertise: ["Banking Services", "Cash Access", "Financial Inclusion"],
    interests: ["Community banking", "Cash services", "Banking hubs"],
    avatar: "POL",
    bio: "UK's largest retail network with 11,500 branches providing essential banking services for major UK banks, offering face-to-face banking, cash services and financial products to underserved communities nationwide",
    marketSegments: ["Retail customers", "SMEs", "Community banking", "Underbanked"],
    geographicFocus: ["UK", "Urban areas", "Rural communities"],
    solutionTypes: ["Banking Services", "Financial Products", "Payment Services"],
    deliveryModels: ["Branch network", "Banking hubs", "Agent services"],
    employeeCount: "10000+",
    recentInitiatives: ["Banking hubs expansion", "Partnership with LINK", "Travel money services", "Savings products via Bank of Ireland UK"],
    partnershipEcosystem: ["UK banks", "Building societies", "LINK", "Bank of Ireland UK", "OneFamily"],
    regulatoryExpertise: ["FCA authorisation", "Cash access regulations", "Banking standards", "Consumer protection"],
    industryRecognition: ["Largest UK branch network", "Community banking champion", "Essential cash infrastructure", "11,500 branches nationwide"]
  },
  {
    id: 20,
    company: "Santander",
    expertise: ["Retail Banking", "Corporate Banking", "Digital Payments"],
    interests: ["Open banking", "Digital transformation", "Sustainable finance"],
    avatar: "SAN",
    bio: "Major UK and global banking group with 160 years heritage, delivering comprehensive retail, business and corporate banking services with leading digital capabilities and open banking platform",
    marketSegments: ["Retail customers", "SMEs", "Corporates", "Institutional clients"],
    geographicFocus: ["UK", "Europe", "Americas", "Global"],
    solutionTypes: ["Banking Services", "Payment Solutions", "Digital Platform"],
    deliveryModels: ["Digital-first", "Branch network", "Mobile banking", "API platform"],
    employeeCount: "1000+",
    recentInitiatives: ["PagoNxt fintech arm", "Open banking expansion", "Digital wallet integration", "Sustainable finance commitments"],
    partnershipEcosystem: ["PagoNxt", "Fintech partners", "Payment schemes", "The Payments Association"],
    regulatoryExpertise: ["UK banking regulations", "PSD2 compliance", "Open Banking Standards", "International financial regulations"],
    industryRecognition: ["Major UK high street bank", "160 years heritage", "Leading digital banking", "Global payments innovation"]
  },
  {
    id: 21,
    company: "Swift",
    expertise: ["Financial Messaging", "Payment Instructions", "Standards Development"],
    interests: ["ISO 20022", "Instant payments", "Digital currencies"],
    avatar: "SWI",
    bio: "Global financial messaging network founded in 1973, enabling secure transmission of payment instructions between 11,000+ institutions across 212 countries, processing 42+ million messages daily",
    marketSegments: ["Banks", "FMIs", "Corporates", "Securities firms"],
    geographicFocus: ["Global", "Europe", "Americas", "Asia Pacific", "MEA"],
    solutionTypes: ["Messaging Platform", "Standards", "Business Intelligence"],
    deliveryModels: ["SWIFTNet", "Alliance services", "Cloud connectivity"],
    employeeCount: "1000+",
    recentInitiatives: ["ISO 20022 migration", "Swift GPI", "Swift Go", "Instant cross-border payments"],
    partnershipEcosystem: ["Central banks", "Payment systems", "Securities infrastructures", "ISO"],
    regulatoryExpertise: ["International standards", "Sanctions compliance", "Cyber security framework", "ISO messaging standards"],
    industryRecognition: ["Global messaging standard", "11,000+ institutions", "212 countries", "99.999% availability"]
  },
  {
    id: 22,
    company: "Tata Consultancy Services Limited",
    expertise: ["IT Services", "Banking Technology", "Digital Transformation"],
    interests: ["Core banking", "Payment platforms", "Cloud migration"],
    avatar: "TCS",
    bio: "Global IT services and consulting leader with 607,000+ associates, delivering TCS BaNCS platform to 450+ financial institutions worldwide, specialising in banking, payments and financial services transformation",
    marketSegments: ["Banks", "Financial institutions", "Insurance", "Capital markets"],
    geographicFocus: ["Global", "Europe", "Americas", "Asia Pacific", "MEA"],
    solutionTypes: ["Software Platforms", "IT Services", "BPO Services"],
    deliveryModels: ["Cloud SaaS", "On-premise", "Managed services", "Consulting"],
    employeeCount: "607000+",
    recentInitiatives: ["TCS BaNCS real-time payments", "Cloud transformation", "AI and automation", "Banking operations leader"],
    partnershipEcosystem: ["Major global banks", "Payment networks", "Technology partners", "Industry bodies"],
    regulatoryExpertise: ["Global banking regulations", "Payment compliance", "Data protection", "Industry standards"],
    industryRecognition: ["Everest Group Leader", "TCS BaNCS 450+ clients", "Fortune India 500", "$25B+ revenue"]
  },
  {
    id: 23,
    company: "Travers Smith LLP",
    expertise: ["Financial Services Law", "Payments Regulation", "Fintech Advisory"],
    interests: ["Market infrastructure", "Digital assets", "Open banking"],
    avatar: "TS",
    bio: "Leading UK commercial law firm with market-leading Fintech, Market Infrastructure and Payments practice, advising on wholesale and retail payments, FMIs, digital assets and innovative financial systems",
    marketSegments: ["FMIs", "Payment institutions", "Banks", "Fintechs"],
    geographicFocus: ["UK", "Europe", "Global cross-border"],
    solutionTypes: ["Legal Advisory", "Regulatory Counsel", "Transaction Services"],
    deliveryModels: ["Legal services", "Regulatory advisory", "Project counsel"],
    employeeCount: "500-1000",
    recentInitiatives: ["Pay.UK New Payments Architecture", "NatWest review", "Fintech incubator programme", "RTGS.global advisory"],
    partnershipEcosystem: ["Payment systems", "Industry associations", "The Payments Association", "Regulatory bodies"],
    regulatoryExpertise: ["Payment systems regulation", "FMI frameworks", "Digital assets regulation", "Financial services law"],
    industryRecognition: ["Silver Circle law firm", "UK Law Firm of Year", "Leading fintech practice", "£215M revenue"]
  },
  {
    id: 24,
    company: "TSYS",
    expertise: ["Card Issuing", "Payment Processing", "Merchant Services"],
    interests: ["Cloud-native platforms", "API-first processing", "Digital wallets"],
    avatar: "TSY",
    bio: "Leading third-party issuer processor in US, Canada, UK and Ireland, processing 35+ billion transactions annually across 875 million accounts with cloud-native, API-driven platform for credit and debit cards",
    marketSegments: ["Banks", "Fintechs", "Retailers", "Corporates"],
    geographicFocus: ["US", "Canada", "UK", "Ireland", "Global"],
    solutionTypes: ["Issuer Processing", "Merchant Services", "Card Management"],
    deliveryModels: ["Cloud platform", "API-first", "Managed services", "SaaS"],
    employeeCount: "10000+",
    recentInitiatives: ["FIS acquisition 2025", "Cloud-native transformation", "Commercial card leadership", "Digital payments expansion"],
    partnershipEcosystem: ["Global Payments", "FIS", "Card networks", "Major banks"],
    regulatoryExpertise: ["PCI compliance", "80+ countries regulation", "Card network rules", "Financial services frameworks"],
    industryRecognition: ["40% US market share", "35B+ transactions", "Technology leader", "Commercial cards leader"]
  },
  {
    id: 25,
    company: "Worldline",
    expertise: ["Merchant Acquiring", "Payment Processing", "Digital Commerce"],
    interests: ["Omnichannel payments", "Payment orchestration", "Embedded finance"],
    avatar: "WDL",
    bio: "Europe's leading payment service provider processing 13+ billion transactions annually, offering comprehensive acquiring, issuing and digital payment services across 50+ countries with extensive local payment method coverage",
    marketSegments: ["Retailers", "Banks", "Fintechs", "Public sector"],
    geographicFocus: ["Europe", "Global", "UK", "France", "DACH"],
    solutionTypes: ["Acquiring Services", "Payment Gateway", "Issuing Platform"],
    deliveryModels: ["In-store", "Online", "Omnichannel", "API platform"],
    employeeCount: "10000+",
    recentInitiatives: ["Crédit Agricole partnership", "Mobility services", "Digital wallet integration", "Cross-border expansion"],
    partnershipEcosystem: ["Banks", "Payment networks", "Technology partners", "Retailers"],
    regulatoryExpertise: ["European payment regulations", "PSD2 compliance", "Card scheme rules", "Multi-country licensing"],
    industryRecognition: ["European PayTech leader", "CAC 40 company", "€4.6B revenue", "250,000+ merchants"]
  },
  {
    id: 26,
    company: "Worldpay",
    expertise: ["Merchant Acquiring", "Global Payments", "E-commerce Solutions"],
    interests: ["Embedded payments", "Alternative payment methods", "Payment orchestration"],
    avatar: "WPY",
    bio: "Major global payment processor handling $2.2 trillion in transactions annually across 146 countries, serving 1.4M+ merchants with comprehensive in-store, online and omnichannel payment solutions",
    marketSegments: ["Enterprises", "SMEs", "E-commerce", "Software platforms"],
    geographicFocus: ["Global", "US", "UK", "Europe", "Asia Pacific"],
    solutionTypes: ["Merchant Services", "Payment Gateway", "Global Acquiring"],
    deliveryModels: ["In-store", "Online", "Mobile", "Integrated payments"],
    employeeCount: "8500+",
    recentInitiatives: ["Global Payments acquisition 2025", "Tap to Pay on iPhone", "ISV partnerships", "Alternative payment methods"],
    partnershipEcosystem: ["Global Payments", "GTCR", "Card networks", "Software platforms"],
    regulatoryExpertise: ["Multi-country licensing", "PCI compliance", "Payment regulations", "135 currencies support"],
    industryRecognition: ["40B+ transactions", "$2.2T annual volume", "Leading global acquirer", "146 countries coverage"]
  },
  {
    id: 27,
    company: "A&O Shearman",
    expertise: ["Financial Services Law", "Banking Regulation", "Capital Markets"],
    interests: ["Payments law", "Fintech", "Regulatory compliance"],
    avatar: "AOS",
    bio: "Global law firm formed from the 2024 merger of Magic Circle Allen & Overy and Shearman & Sterling, creating the world's third-largest law firm with 4,000+ lawyers advising on complex financial services, payments and regulatory matters",
    marketSegments: ["Banks", "Financial institutions", "Payment providers", "Corporates"],
    geographicFocus: ["Global", "UK", "US", "Europe", "Asia"],
    solutionTypes: ["Legal Advisory", "Regulatory Counsel", "Transaction Services"],
    deliveryModels: ["Legal services", "M&A advisory", "Compliance counsel"],
    employeeCount: "4000+",
    recentInitiatives: ["Allen & Overy and Shearman merger 2024", "Harvey AI implementation", "ContractMatrix AI tool", "Financial Times Most Innovative Law Firm 2024"],
    partnershipEcosystem: ["Regulators", "Industry bodies", "Financial institutions", "Global law firms"],
    regulatoryExpertise: ["Banking regulation", "Payments law", "Financial services regulation", "Capital markets law"],
    industryRecognition: ["World's 3rd largest law firm", "Magic Circle", "£2.9B revenue", "FT Most Innovative 2024"]
  },
  {
    id: 28,
    company: "Accenture",
    expertise: ["IT Consulting", "Digital Transformation", "Banking Technology"],
    interests: ["Cloud transformation", "AI and automation", "Payment modernisation"],
    avatar: "ACN",
    bio: "Global professional services leader with 791,000+ professionals, delivering the Bank of England's RTGS renewal and providing comprehensive banking, payments and financial services transformation across 120+ countries",
    marketSegments: ["Banks", "Payment providers", "Financial institutions", "Capital markets"],
    geographicFocus: ["Global", "UK", "Europe", "Americas", "Asia Pacific"],
    solutionTypes: ["Consulting Services", "Technology Solutions", "Managed Services"],
    deliveryModels: ["Strategy consulting", "Technology implementation", "Managed services", "Cloud platforms"],
    employeeCount: "791000+",
    recentInitiatives: ["Bank of England RTGS renewal", "BCS Consulting acquisition", "Open banking solutions", "Payment transformation programmes"],
    partnershipEcosystem: ["Technology providers", "Central banks", "Financial institutions", "Industry bodies"],
    regulatoryExpertise: ["Payment regulations", "Banking compliance", "Data protection", "Global financial frameworks"],
    industryRecognition: ["RTGS transformation delivery", "Global consulting leader", "Banking technology expert", "Payment innovation pioneer"]
  },
  {
    id: 29,
    company: "Accomplish Financial",
    expertise: ["Payment Solutions", "Fintech Services", "Financial Technology"],
    interests: ["Digital payments", "Financial innovation", "Payment processing"],
    avatar: "ACF",
    bio: "UK-based financial technology company providing innovative payment solutions and financial services to businesses and consumers across multiple sectors",
    marketSegments: ["SMEs", "Consumers", "Businesses"],
    geographicFocus: ["UK", "Europe"],
    solutionTypes: ["Payment Solutions", "Financial Services", "Technology Platform"],
    deliveryModels: ["Digital platform", "API services", "Managed solutions"],
    employeeCount: "50-250",
    recentInitiatives: ["Digital payment expansion", "Product innovation", "Market growth"],
    partnershipEcosystem: ["Payment providers", "Financial institutions", "Technology partners"],
    regulatoryExpertise: ["FCA regulation", "Payment regulations", "Financial services compliance"],
    industryRecognition: ["Fintech innovator", "UK payments specialist"]
  },
  {
    id: 30,
    company: "Algbra",
    expertise: ["Islamic Finance", "Ethical Banking", "Digital Payments"],
    interests: ["Shariah-compliant finance", "Financial inclusion", "Ethical banking"],
    avatar: "ALG",
    bio: "UK fintech providing ethical, Shariah-compliant banking and payment solutions, serving underserved communities with innovative digital financial services aligned with Islamic principles",
    marketSegments: ["Muslim community", "Ethical consumers", "Underbanked"],
    geographicFocus: ["UK", "Europe", "Global Muslim markets"],
    solutionTypes: ["Digital Banking", "Payment Cards", "Ethical Finance"],
    deliveryModels: ["Mobile app", "Digital platform", "Prepaid cards"],
    employeeCount: "50-250",
    recentInitiatives: ["Shariah-compliant product development", "Financial inclusion programmes", "Digital banking expansion"],
    partnershipEcosystem: ["Islamic finance bodies", "Payment processors", "Ethical investors"],
    regulatoryExpertise: ["FCA regulation", "Islamic finance standards", "Payment regulations"],
    industryRecognition: ["Islamic fintech pioneer", "Ethical banking champion", "Financial inclusion advocate"]
  },
  {
    id: 31,
    company: "AlixPartners",
    expertise: ["Management Consulting", "Financial Restructuring", "Performance Improvement"],
    interests: ["Banking transformation", "Operational efficiency", "Digital strategy"],
    avatar: "ALX",
    bio: "Global consulting firm specialising in business transformation and turnaround, advising financial services firms on performance improvement, restructuring and operational excellence in complex situations",
    marketSegments: ["Banks", "Financial institutions", "Corporates", "Private equity"],
    geographicFocus: ["Global", "UK", "Europe", "Americas", "Asia"],
    solutionTypes: ["Consulting Services", "Restructuring Advisory", "Performance Improvement"],
    deliveryModels: ["Strategy consulting", "Hands-on implementation", "Interim management"],
    employeeCount: "3000+",
    recentInitiatives: ["Financial services transformation", "Digital banking programmes", "Cost optimisation initiatives"],
    partnershipEcosystem: ["Financial institutions", "Private equity firms", "Regulators"],
    regulatoryExpertise: ["Banking regulations", "Restructuring frameworks", "Compliance advisory"],
    industryRecognition: ["Restructuring specialist", "Performance improvement leader", "Financial services expert"]
  },
  {
    id: 32,
    company: "Allica Bank",
    expertise: ["SME Banking", "Business Banking", "Digital Lending"],
    interests: ["SME finance", "Digital banking", "Relationship banking"],
    avatar: "ALB",
    bio: "UK challenger bank dedicated to serving established SMEs with tailored business banking, lending and deposit solutions, combining digital efficiency with relationship banking expertise",
    marketSegments: ["SMEs", "Established businesses", "Growth companies"],
    geographicFocus: ["UK"],
    solutionTypes: ["Business Banking", "Commercial Lending", "Deposit Accounts"],
    deliveryModels: ["Digital banking", "Relationship management", "Branch-lite model"],
    employeeCount: "250-500",
    recentInitiatives: ["SME lending expansion", "Digital platform enhancement", "Relationship banking model", "Growth capital raising"],
    partnershipEcosystem: ["SME organisations", "Business advisors", "Industry bodies"],
    regulatoryExpertise: ["PRA authorisation", "FCA regulation", "Banking regulations", "SME finance frameworks"],
    industryRecognition: ["SME banking specialist", "UK challenger bank", "Digital-first approach"]
  },
  {
    id: 33,
    company: "allpay",
    expertise: ["Bill Payments", "Public Sector Payments", "Payment Processing"],
    interests: ["Social housing", "Local government", "Payment accessibility"],
    avatar: "APY",
    bio: "UK market leader in public sector payment services, processing £8.5B annually for 50%+ of local authorities and 90% of top 200 housing associations, serving 4.5M+ customers with accessible payment solutions",
    marketSegments: ["Housing associations", "Local authorities", "Central government", "Credit unions"],
    geographicFocus: ["UK"],
    solutionTypes: ["Payment Processing", "Card Services", "Bill Payment Solutions"],
    deliveryModels: ["Payment cards", "Online payments", "PayPoint network", "Direct debit"],
    employeeCount: "250-500",
    recentInitiatives: ["Bank of London partnership", "Digital payment expansion", "Prepaid card services", "Financial inclusion initiatives"],
    partnershipEcosystem: ["Housing providers", "Local authorities", "PayPoint", "The Bank of London"],
    regulatoryExpertise: ["FCA regulation", "Public sector compliance", "Payment regulations", "Data protection"],
    industryRecognition: ["Public sector market leader", "50% local authority coverage", "£8.5B annual processing", "4.5M customers"]
  },
  {
    id: 34,
    company: "American Express",
    expertise: ["Card Issuing", "Merchant Services", "Payment Processing"],
    interests: ["Premium services", "Open banking", "Digital payments"],
    avatar: "AMEX",
    bio: "Global payments and travel company with 114.4M+ cardmembers worldwide, operating closed-loop network as both issuer and acquirer, known for premium cards and high-spending customer base in 130+ countries",
    marketSegments: ["Premium consumers", "Corporates", "SMEs", "Travel sector"],
    geographicFocus: ["Global", "UK", "US", "Europe", "Asia Pacific"],
    solutionTypes: ["Credit Cards", "Charge Cards", "Merchant Services"],
    deliveryModels: ["Closed-loop network", "Merchant acquiring", "Corporate services"],
    employeeCount: "10000+",
    recentInitiatives: ["Pay with Bank transfer", "Open banking integration", "SafeKey 3D Secure", "Merchant expansion"],
    partnershipEcosystem: ["Merchant acquirers", "Payment gateways", "Banks", "Travel partners"],
    regulatoryExpertise: ["PCI compliance", "Payment regulations", "Banking regulations", "Global financial frameworks"],
    industryRecognition: ["114.4M cardmembers", "Premium payments leader", "130+ countries", "2.7x higher UK spend"]
  },
  {
    id: 35,
    company: "AML RightSource",
    expertise: ["AML Compliance", "Financial Crime Prevention", "Regulatory Technology"],
    interests: ["Transaction monitoring", "KYC services", "Compliance solutions"],
    avatar: "AML",
    bio: "Global provider of anti-money laundering and compliance services, delivering managed services, technology solutions and expert resources to financial institutions for regulatory compliance and financial crime prevention",
    marketSegments: ["Banks", "Payment providers", "Financial institutions", "Fintechs"],
    geographicFocus: ["Global", "UK", "US", "Europe"],
    solutionTypes: ["AML Services", "Compliance Technology", "Managed Services"],
    deliveryModels: ["Managed services", "Technology solutions", "Expert advisory"],
    employeeCount: "1000+",
    recentInitiatives: ["RegTech solutions", "AI-powered monitoring", "Global compliance expansion"],
    partnershipEcosystem: ["Financial institutions", "RegTech providers", "Regulators"],
    regulatoryExpertise: ["AML regulations", "KYC requirements", "Financial crime frameworks", "Global compliance standards"],
    industryRecognition: ["AML specialist", "Global compliance provider", "RegTech leader"]
  },
  {
    id: 36,
    company: "Andaria",
    expertise: ["Payment Technology", "Software Solutions", "Financial Services"],
    interests: ["Payment innovation", "Digital solutions", "Technology services"],
    avatar: "AND",
    bio: "Technology solutions provider delivering innovative payment and financial services software to banks and financial institutions, specialising in digital transformation and payment modernisation",
    marketSegments: ["Banks", "Financial institutions", "Payment providers"],
    geographicFocus: ["UK", "Europe"],
    solutionTypes: ["Software Solutions", "Payment Technology", "Integration Services"],
    deliveryModels: ["Software platforms", "Technology consulting", "Integration services"],
    employeeCount: "50-250",
    recentInitiatives: ["Payment platform development", "Digital transformation projects", "Technology partnerships"],
    partnershipEcosystem: ["Financial institutions", "Technology providers", "Payment systems"],
    regulatoryExpertise: ["Payment regulations", "Technology compliance", "Financial services standards"],
    industryRecognition: ["Payment technology specialist", "Financial services innovator"]
  },
  {
    id: 37,
    company: "Arf",
    expertise: ["Payment Solutions", "Financial Technology", "Digital Services"],
    interests: ["Payment innovation", "Fintech services", "Digital finance"],
    avatar: "ARF",
    bio: "Financial technology company providing innovative payment solutions and digital financial services, supporting businesses with modern payment infrastructure and technology platforms",
    marketSegments: ["Businesses", "SMEs", "Consumers"],
    geographicFocus: ["UK", "Europe"],
    solutionTypes: ["Payment Platform", "Digital Solutions", "Technology Services"],
    deliveryModels: ["Digital platform", "API services", "Technology solutions"],
    employeeCount: "50-250",
    recentInitiatives: ["Payment technology development", "Platform expansion", "Digital services growth"],
    partnershipEcosystem: ["Payment providers", "Technology partners", "Financial institutions"],
    regulatoryExpertise: ["Payment regulations", "FCA compliance", "Financial services frameworks"],
    industryRecognition: ["Payment technology provider", "Fintech innovator"]
  },
  {
    id: 38,
    company: "Ashurst LLP",
    expertise: ["Financial Services Law", "Banking Regulation", "Fintech Advisory"],
    interests: ["Payment systems", "Digital assets", "Regulatory compliance"],
    avatar: "ASH",
    bio: "International law firm with strong financial services practice, advising banks, payment institutions and fintechs on regulatory compliance, transactions and innovative payment solutions across global markets",
    marketSegments: ["Banks", "Payment institutions", "Fintechs", "Corporates"],
    geographicFocus: ["Global", "UK", "Europe", "Asia Pacific"],
    solutionTypes: ["Legal Advisory", "Regulatory Counsel", "Transaction Services"],
    deliveryModels: ["Legal services", "Regulatory advisory", "Transaction support"],
    employeeCount: "1000+",
    recentInitiatives: ["Fintech advisory expansion", "Payment systems regulation", "Digital assets practice"],
    partnershipEcosystem: ["Financial institutions", "Regulators", "Industry bodies", "Payment systems"],
    regulatoryExpertise: ["Financial services regulation", "Payment systems law", "Digital assets regulation", "Banking law"],
    industryRecognition: ["Top-tier financial services practice", "Payment systems expertise", "Global law firm"]
  },
  {
    id: 39,
    company: "Attenda",
    expertise: ["Payment Technology", "Software Solutions", "Financial Services"],
    interests: ["Payment processing", "Technology platforms", "Digital solutions"],
    avatar: "ATT",
    bio: "Technology solutions provider specialising in payment processing and financial services software, delivering innovative platforms for banks and financial institutions to enhance payment capabilities",
    marketSegments: ["Banks", "Financial institutions", "Payment providers"],
    geographicFocus: ["UK", "Europe"],
    solutionTypes: ["Software Platform", "Payment Technology", "Technology Services"],
    deliveryModels: ["Software solutions", "Technology platform", "Professional services"],
    employeeCount: "50-250",
    recentInitiatives: ["Payment platform enhancement", "Technology partnerships", "Digital transformation"],
    partnershipEcosystem: ["Financial institutions", "Technology providers", "Payment networks"],
    regulatoryExpertise: ["Payment regulations", "Technology compliance", "Financial services standards"],
    industryRecognition: ["Payment technology provider", "Financial services specialist"]
  },
  {
    id: 40,
    company: "Aurum Solutions",
    expertise: ["Wealth Management Technology", "Financial Software", "Digital Solutions"],
    interests: ["Digital wealth", "Platform solutions", "Technology innovation"],
    avatar: "AUR",
    bio: "Leading provider of technology solutions for the wealth management industry, delivering innovative platforms and software to wealth managers, private banks and financial advisors across global markets",
    marketSegments: ["Wealth managers", "Private banks", "Financial advisors", "Asset managers"],
    geographicFocus: ["Global", "UK", "Europe", "Asia"],
    solutionTypes: ["Technology Platform", "Software Solutions", "Advisory Services"],
    deliveryModels: ["SaaS platform", "Software licensing", "Managed services"],
    employeeCount: "100-500",
    recentInitiatives: ["Platform development", "Digital wealth solutions", "Technology partnerships"],
    partnershipEcosystem: ["Wealth managers", "Technology providers", "Financial institutions"],
    regulatoryExpertise: ["Wealth management regulations", "FCA compliance", "Data protection"],
    industryRecognition: ["Wealth tech leader", "Platform specialist", "Financial services innovator"]
  },
  {
    id: 41,
    company: "AutoRek",
    expertise: ["Financial Reconciliation", "Transaction Matching", "Automation Software"],
    interests: ["Automated reconciliation", "Financial controls", "Payment matching"],
    avatar: "ARK",
    bio: "Leading provider of automated financial reconciliation and transaction matching solutions, serving banks, payment companies and corporates with AI-powered software for complex financial operations and controls",
    marketSegments: ["Banks", "Payment companies", "Corporates", "Asset managers"],
    geographicFocus: ["Global", "UK", "Europe", "Americas", "Asia"],
    solutionTypes: ["Reconciliation Software", "Automation Platform", "Financial Controls"],
    deliveryModels: ["SaaS platform", "Cloud-based", "On-premise"],
    employeeCount: "250-500",
    recentInitiatives: ["AI-powered reconciliation", "Cloud platform expansion", "Payment reconciliation solutions"],
    partnershipEcosystem: ["Banks", "Payment processors", "Technology providers", "System integrators"],
    regulatoryExpertise: ["Financial controls", "Audit requirements", "Payment regulations", "Risk management"],
    industryRecognition: ["Reconciliation market leader", "Automation specialist", "Global coverage"]
  },
  {
    id: 42,
    company: "Baker McKenzie",
    expertise: ["International Law", "Financial Services", "Regulatory Compliance"],
    interests: ["Payments law", "Fintech regulation", "Cross-border transactions"],
    avatar: "BMK",
    bio: "Global law firm with extensive financial services and payments practice, advising banks, payment institutions and fintechs on complex regulatory matters, transactions and cross-border operations across 70+ countries",
    marketSegments: ["Banks", "Payment institutions", "Fintechs", "Corporates"],
    geographicFocus: ["Global", "UK", "Europe", "Americas", "Asia Pacific", "MEA"],
    solutionTypes: ["Legal Advisory", "Regulatory Counsel", "Transaction Services"],
    deliveryModels: ["Legal services", "Compliance advisory", "Transaction support"],
    employeeCount: "10000+",
    recentInitiatives: ["Fintech practice expansion", "Payment regulations advisory", "Digital assets expertise"],
    partnershipEcosystem: ["Financial institutions", "Regulators", "Industry bodies", "Global law firms"],
    regulatoryExpertise: ["Financial services regulation", "Payment systems law", "Cross-border regulations", "Fintech compliance"],
    industryRecognition: ["Global law firm leader", "70+ countries", "Financial services specialist", "Payments expertise"]
  },
  {
    id: 43,
    company: "Bank of America",
    expertise: ["Global Banking", "Payment Services", "Treasury Management"],
    interests: ["Digital banking", "Corporate payments", "Treasury solutions"],
    avatar: "BAC",
    bio: "Major US global bank serving UK and international markets with comprehensive banking, payments and treasury services for corporates, institutions and high-net-worth clients through extensive global network",
    marketSegments: ["Corporates", "Institutions", "HNWI", "SMEs"],
    geographicFocus: ["Global", "US", "UK", "Europe", "Asia Pacific"],
    solutionTypes: ["Corporate Banking", "Payment Services", "Treasury Solutions"],
    deliveryModels: ["Branch network", "Digital banking", "Relationship banking"],
    employeeCount: "10000+",
    recentInitiatives: ["Digital transformation", "Payment innovation", "Treasury technology", "Sustainable finance"],
    partnershipEcosystem: ["Payment networks", "Technology providers", "Financial institutions", "Corporates"],
    regulatoryExpertise: ["US banking regulations", "UK regulations", "Global compliance", "AML frameworks"],
    industryRecognition: ["Major US bank", "Global presence", "Corporate banking leader", "Treasury specialist"]
  },
  {
    id: 44,
    company: "Banking Circle",
    expertise: ["Cross-border Payments", "Banking Infrastructure", "Virtual IBANs"],
    interests: ["B2B payments", "Payment technology", "Fintech banking"],
    avatar: "BC",
    bio: "Luxembourg-licensed bank providing revolutionary banking infrastructure for payments businesses, banks and investment funds, processing billions in transactions with modern cloud-based technology and instant settlement capabilities",
    marketSegments: ["Payment providers", "Banks", "Fintechs", "Investment funds"],
    geographicFocus: ["Global", "Europe", "UK", "Americas", "Asia"],
    solutionTypes: ["Banking Infrastructure", "Payment Processing", "Virtual Accounts"],
    deliveryModels: ["Cloud platform", "API-first", "Virtual IBANs", "Real-time settlement"],
    employeeCount: "500-1000",
    recentInitiatives: ["Cloud-based platform", "BC-NOW instant settlement", "SEPA Instant integration", "B2B payment expansion"],
    partnershipEcosystem: ["Payment institutions", "Banks", "Fintechs", "Technology providers"],
    regulatoryExpertise: ["EU banking regulations", "Payment regulations", "PSD2 compliance", "Multi-jurisdictional licensing"],
    industryRecognition: ["10% B2C e-commerce flow", "€100B B2B processing", "Cloud-native pioneer", "Payments bank"]
  },
  {
    id: 45,
    company: "Barclays",
    expertise: ["Retail Banking", "Corporate Banking", "Investment Banking"],
    interests: ["Digital banking", "Payment innovation", "Open banking"],
    avatar: "BAR",
    bio: "Major UK high street bank and global financial services provider offering comprehensive retail, business and corporate banking with extensive UK branch network and leading digital capabilities across international markets",
    marketSegments: ["Retail customers", "SMEs", "Corporates", "Institutions"],
    geographicFocus: ["UK", "US", "Europe", "Global"],
    solutionTypes: ["Banking Services", "Payment Solutions", "Investment Services"],
    deliveryModels: ["Branch network", "Digital banking", "Mobile app", "Corporate services"],
    employeeCount: "10000+",
    recentInitiatives: ["Digital transformation", "Post Office banking services", "Payment innovation", "Sustainable finance"],
    partnershipEcosystem: ["Post Office", "Payment schemes", "Fintechs", "Industry bodies"],
    regulatoryExpertise: ["UK banking regulations", "PRA/FCA regulation", "Payment regulations", "Global compliance"],
    industryRecognition: ["Major UK bank", "Global presence", "Digital banking leader", "Universal bank"]
  },
  {
    id: 46,
    company: "BCB Group",
    expertise: ["Digital Asset Banking", "Crypto Payments", "Fiat-Crypto Services"],
    interests: ["Stablecoin payments", "Blockchain infrastructure", "Digital asset custody"],
    avatar: "BCB",
    bio: "Leading crypto-dedicated payment services provider regulated in UK, France and Switzerland, processing $200B+ annually in fiat payments and serving major crypto exchanges with BLINC instant settlement network",
    marketSegments: ["Crypto exchanges", "Digital asset firms", "Payment providers", "Investment funds"],
    geographicFocus: ["Global", "UK", "Europe", "US"],
    solutionTypes: ["Payment Services", "Trading Platform", "Digital Asset Custody"],
    deliveryModels: ["API platform", "BLINC network", "Multi-currency accounts", "24/7 settlement"],
    employeeCount: "250-500",
    recentInitiatives: ["Mambu partnership", "USDC integration", "USD BLINC expansion", "French EMI authorisation"],
    partnershipEcosystem: ["Bitstamp", "Coinbase", "Gemini", "Kraken", "Circle", "Fireblocks"],
    regulatoryExpertise: ["FCA regulation", "French EMI", "Swiss regulation", "Digital assets frameworks"],
    industryRecognition: ["$200B annual processing", "250+ clients", "Crypto banking leader", "BLINC network"]
  },
  {
    id: 47,
    company: "BDO LLP",
    expertise: ["Audit & Assurance", "Tax Advisory", "Business Consulting"],
    interests: ["Financial services", "Alternative finance", "E-money services"],
    avatar: "BDO",
    bio: "Fifth-largest global accounting network with 7,500 UK professionals across 18 offices, providing audit, tax and advisory services to financial services sector including payment companies, e-money providers and alternative finance firms",
    marketSegments: ["Banks", "Payment providers", "Fintechs", "Corporates"],
    geographicFocus: ["UK", "Global", "Europe", "Americas", "Asia"],
    solutionTypes: ["Audit Services", "Tax Advisory", "Business Consulting"],
    deliveryModels: ["Professional services", "Advisory", "Outsourcing"],
    employeeCount: "7500",
    recentInitiatives: ["Moore Stephens merger 2019", "Financial services sector expansion", "Alternative finance expertise"],
    partnershipEcosystem: ["Financial institutions", "Payment companies", "Regulatory bodies", "Industry associations"],
    regulatoryExpertise: ["Financial services regulations", "Audit standards", "Tax compliance", "Payment regulations"],
    industryRecognition: ["5th largest accounting network", "$15B global revenue", "166 countries", "UK financial services specialist"]
  },
  {
    id: 48,
    company: "Bird & Bird",
    expertise: ["Technology Law", "Financial Services", "Payments Regulation"],
    interests: ["PSD2", "Open banking", "Fintech innovation"],
    avatar: "BB",
    bio: "International law firm with 1,600+ lawyers across 32 offices, specialising in technology-driven sectors with leading payments and fintech practice advising on PSD2, e-money and innovative payment solutions",
    marketSegments: ["Payment providers", "Fintechs", "Banks", "Tech companies"],
    geographicFocus: ["Global", "UK", "Europe", "Asia Pacific", "Middle East"],
    solutionTypes: ["Legal Advisory", "Regulatory Counsel", "Technology Law"],
    deliveryModels: ["Legal services", "Compliance advisory", "Transaction support"],
    employeeCount: "1600+",
    recentInitiatives: ["Payments Association partnership", "PSD2 advisory", "Blockchain and crypto expertise", "Open banking guidance"],
    partnershipEcosystem: ["Financial institutions", "Regulators", "The Payments Association", "Technology providers"],
    regulatoryExpertise: ["PSD2 compliance", "Payment services regulation", "E-money frameworks", "Strong Customer Authentication"],
    industryRecognition: ["Leading fintech practice", "Payments specialist", "FT innovative firm", "32 global offices"]
  },
  {
    id: 49,
    company: "Blue Train Marketing",
    expertise: ["Marketing Services", "Brand Strategy", "Digital Marketing"],
    interests: ["Fintech marketing", "B2B services", "Digital transformation"],
    avatar: "BTM",
    bio: "Specialist marketing agency serving financial services and payments sector, delivering strategic marketing, brand development and digital campaigns for banks, fintechs and payment companies",
    marketSegments: ["Financial services", "Fintechs", "Payment providers", "Technology companies"],
    geographicFocus: ["UK", "Europe"],
    solutionTypes: ["Marketing Strategy", "Brand Development", "Digital Campaigns"],
    deliveryModels: ["Agency services", "Strategic consulting", "Campaign execution"],
    employeeCount: "10-50",
    recentInitiatives: ["Financial services marketing", "Fintech sector focus", "Digital marketing expansion"],
    partnershipEcosystem: ["Financial institutions", "Fintechs", "Payment providers", "Industry events"],
    regulatoryExpertise: ["Financial marketing regulations", "Compliance guidelines", "Industry standards"],
    industryRecognition: ["Financial services specialist", "B2B marketing expert"]
  },
  {
    id: 50,
    company: "Boston Consulting Group",
    expertise: ["Management Consulting", "Digital Transformation", "Financial Services"],
    interests: ["Payment innovation", "Digital banking", "Platform economics"],
    avatar: "BCG",
    bio: "Global management consulting leader with extensive financial services practice, advising banks and payment providers on strategy, digital transformation and operational excellence across 100+ countries",
    marketSegments: ["Banks", "Payment providers", "Fintechs", "Corporates"],
    geographicFocus: ["Global", "UK", "Europe", "Americas", "Asia Pacific"],
    solutionTypes: ["Strategy Consulting", "Digital Transformation", "Technology Advisory"],
    deliveryModels: ["Management consulting", "Implementation support", "Strategic advisory"],
    employeeCount: "25000+",
    recentInitiatives: ["Payment transformation programmes", "Digital banking strategy", "Open banking advisory", "Fintech partnerships"],
    partnershipEcosystem: ["Financial institutions", "Technology providers", "Governments", "Industry bodies"],
    regulatoryExpertise: ["Banking regulations", "Payment frameworks", "Digital transformation compliance"],
    industryRecognition: ["Top 3 global consultancy", "Financial services leader", "Payment innovation expert", "100+ countries"]
  },
  {
    id: 51,
    company: "Bottomline",
    expertise: ["Payment Automation", "Cash Management", "Financial Messaging"],
    interests: ["Digital payments", "Fraud prevention", "Payment orchestration"],
    avatar: "BTL",
    bio: "Global provider of payment automation and cash management solutions, serving banks and corporates with comprehensive payment processing, fraud detection and financial messaging capabilities across multiple payment types",
    marketSegments: ["Banks", "Corporates", "Financial institutions", "Government"],
    geographicFocus: ["Global", "UK", "US", "Europe", "Asia Pacific"],
    solutionTypes: ["Payment Platform", "Fraud Prevention", "Cash Management"],
    deliveryModels: ["SaaS platform", "Cloud-based", "Managed services"],
    employeeCount: "2000+",
    recentInitiatives: ["Cloud transformation", "AI-powered fraud detection", "Payment orchestration", "Open banking integration"],
    partnershipEcosystem: ["Banks", "Payment networks", "Technology providers", "System integrators"],
    regulatoryExpertise: ["Payment regulations", "AML compliance", "SWIFT standards", "ISO 20022"],
    industryRecognition: ["Payment automation leader", "Global presence", "30+ years experience", "Multi-channel solutions"]
  },
  {
    id: 52,
    company: "Burges Salmon LLP",
    expertise: ["Corporate Law", "Financial Services", "Banking Regulation"],
    interests: ["Payments law", "Fintech", "Regulatory compliance"],
    avatar: "BS",
    bio: "Leading UK law firm with strong financial services and payments practice, advising banks, payment institutions and fintechs on regulatory matters, transactions and innovative payment solutions from offices in Bristol, London and Edinburgh",
    marketSegments: ["Banks", "Payment providers", "Fintechs", "Corporates"],
    geographicFocus: ["UK", "Europe", "International"],
    solutionTypes: ["Legal Advisory", "Regulatory Counsel", "Transaction Services"],
    deliveryModels: ["Legal services", "Compliance advisory", "Transaction support"],
    employeeCount: "500-1000",
    recentInitiatives: ["Fintech practice expansion", "Payment regulations advisory", "Open banking guidance", "Digital assets expertise"],
    partnershipEcosystem: ["Financial institutions", "Regulators", "Industry bodies", "Payment systems"],
    regulatoryExpertise: ["Financial services regulation", "Payment systems law", "Banking law", "Fintech compliance"],
    industryRecognition: ["Top-tier UK law firm", "Financial services specialist", "Payments expertise", "Leading regional firm"]
  },
  {
    id: 53,
    company: "Cardlytics",
    expertise: ["Purchase Intelligence", "Card-linked Marketing", "Data Analytics"],
    interests: ["Banking partnerships", "Marketing solutions", "Transaction data"],
    avatar: "CDL",
    bio: "Leading purchase intelligence platform partnering with banks to deliver card-linked marketing and analytics, helping financial institutions monetise transaction data whilst providing targeted offers to cardholders",
    marketSegments: ["Banks", "Retailers", "Brands", "Marketers"],
    geographicFocus: ["Global", "UK", "US", "Europe"],
    solutionTypes: ["Marketing Platform", "Data Analytics", "Card-linked Offers"],
    deliveryModels: ["SaaS platform", "Bank partnerships", "Revenue share"],
    employeeCount: "500-1000",
    recentInitiatives: ["Bank partnership expansion", "AI-powered insights", "Purchase intelligence platform", "Revenue diversification"],
    partnershipEcosystem: ["Banks", "Card schemes", "Retailers", "Brand advertisers"],
    regulatoryExpertise: ["Data protection", "Banking partnerships", "Marketing regulations", "Privacy frameworks"],
    industryRecognition: ["Purchase intelligence leader", "Bank partnerships", "Card-linked marketing pioneer", "Transaction data specialist"]
  },
  {
    id: 54,
    company: "Chargebacks911 and Fi911",
    expertise: ["Chargeback Prevention", "Dispute Management", "Fraud Mitigation"],
    interests: ["Payment protection", "Merchant defence", "Chargeback intelligence"],
    avatar: "CB9",
    bio: "Global leader in chargeback prevention and dispute management, providing comprehensive solutions for merchants and payment providers to reduce chargebacks, prevent fraud and recover revenue through technology and expertise",
    marketSegments: ["Merchants", "Payment providers", "E-commerce", "Financial institutions"],
    geographicFocus: ["Global", "US", "UK", "Europe", "Asia"],
    solutionTypes: ["Chargeback Prevention", "Dispute Management", "Fraud Prevention"],
    deliveryModels: ["SaaS platform", "Managed services", "Consulting"],
    employeeCount: "250-500",
    recentInitiatives: ["AI-powered prevention", "Fi911 financial institution solutions", "Global expansion", "Technology partnerships"],
    partnershipEcosystem: ["Payment processors", "Card schemes", "E-commerce platforms", "Financial institutions"],
    regulatoryExpertise: ["Card scheme rules", "Payment regulations", "Dispute frameworks", "Consumer protection"],
    industryRecognition: ["Chargeback prevention leader", "Global coverage", "Merchant protection specialist", "Fi911 bank solutions"]
  },
  {
    id: 55,
    company: "Cleafy",
    expertise: ["Fraud Prevention", "Digital Banking Security", "Threat Intelligence"],
    interests: ["Mobile security", "Real-time fraud detection", "Behavioural analytics"],
    avatar: "CLF",
    bio: "Leading provider of fraud prevention and online banking security solutions, protecting financial institutions and their customers from digital fraud through advanced threat intelligence and behavioural analytics technology",
    marketSegments: ["Banks", "Financial institutions", "Payment providers", "Fintechs"],
    geographicFocus: ["Global", "Europe", "UK", "Americas"],
    solutionTypes: ["Fraud Prevention Platform", "Security Solutions", "Threat Intelligence"],
    deliveryModels: ["SaaS platform", "Cloud-based", "API integration"],
    employeeCount: "100-250",
    recentInitiatives: ["AI-powered fraud detection", "Mobile security expansion", "Threat intelligence platform", "Banking partnerships"],
    partnershipEcosystem: ["Banks", "Security providers", "Payment processors", "Technology vendors"],
    regulatoryExpertise: ["PSD2 compliance", "Strong Customer Authentication", "Data protection", "Security standards"],
    industryRecognition: ["Fraud prevention specialist", "Digital banking security", "Threat intelligence leader", "Innovation awards"]
  },
  {
    id: 56,
    company: "Clear Junction",
    expertise: ["Payment Processing", "Cross-border Payments", "Banking-as-a-Service"],
    interests: ["Global payments", "Fintech enablement", "Multi-currency solutions"],
    avatar: "CJ",
    bio: "FCA-authorised payment institution providing global payment infrastructure and banking-as-a-service solutions, enabling fintechs and businesses with multi-currency accounts, cross-border payments and embedded finance capabilities",
    marketSegments: ["Fintechs", "Payment providers", "Crypto businesses", "E-commerce"],
    geographicFocus: ["Global", "UK", "Europe", "Americas", "Asia"],
    solutionTypes: ["Payment Processing", "BaaS Platform", "Multi-currency Accounts"],
    deliveryModels: ["API platform", "White-label", "Banking-as-a-Service"],
    employeeCount: "100-250",
    recentInitiatives: ["Global payment expansion", "Crypto integration", "BaaS platform development", "Regulatory approvals"],
    partnershipEcosystem: ["Fintechs", "Crypto exchanges", "Payment providers", "Technology partners"],
    regulatoryExpertise: ["FCA authorisation", "Payment regulations", "Cross-border compliance", "Multi-jurisdictional licensing"],
    industryRecognition: ["FCA-authorised", "BaaS specialist", "Global payment infrastructure", "Fintech enabler"]
  },
  {
    id: 57,
    company: "ClearBank",
    expertise: ["Clearing Services", "Banking Infrastructure", "API Banking"],
    interests: ["Real-time payments", "Embedded banking", "Financial innovation"],
    avatar: "CLB",
    bio: "UK's first new clearing bank in 250 years, providing cloud-based banking infrastructure and real-time clearing services to banks, fintechs and payment companies through modern API-first platform with direct access to UK payment schemes",
    marketSegments: ["Banks", "Fintechs", "Payment institutions", "Asset managers"],
    geographicFocus: ["UK", "Europe expansion"],
    solutionTypes: ["Clearing Services", "Banking-as-a-Service", "Payment Platform"],
    deliveryModels: ["API-first platform", "Cloud-native", "Real-time clearing"],
    employeeCount: "500-1000",
    recentInitiatives: ["European expansion", "Agency banking services", "Real-time payment innovation", "Multi-currency capabilities"],
    partnershipEcosystem: ["Fintechs", "Banks", "Payment providers", "Technology partners", "Mastercard"],
    regulatoryExpertise: ["PRA/FCA regulation", "Payment scheme rules", "Banking regulations", "Clearing standards"],
    industryRecognition: ["First new clearing bank 250 years", "Cloud-native pioneer", "API-first banking", "Direct scheme access"]
  },
  {
    id: 58,
    company: "ComplyAdvantage",
    expertise: ["AML Compliance", "Financial Crime Prevention", "Risk Intelligence"],
    interests: ["AI-powered screening", "Transaction monitoring", "Regulatory technology"],
    avatar: "CA",
    bio: "Leading AI-powered financial crime risk detection platform, providing real-time AML and fraud prevention solutions to banks, fintechs and payment companies through dynamic risk intelligence and advanced screening technology",
    marketSegments: ["Banks", "Fintechs", "Payment providers", "Crypto exchanges"],
    geographicFocus: ["Global", "UK", "US", "Europe", "Asia Pacific"],
    solutionTypes: ["AML Platform", "Risk Intelligence", "Screening Solutions"],
    deliveryModels: ["SaaS platform", "API-first", "Cloud-based"],
    employeeCount: "500-1000",
    recentInitiatives: ["AI-powered screening", "Real-time risk intelligence", "Crypto compliance solutions", "Global expansion"],
    partnershipEcosystem: ["Financial institutions", "RegTech providers", "Payment companies", "Crypto platforms"],
    regulatoryExpertise: ["AML regulations", "KYC requirements", "Sanctions screening", "Global compliance frameworks"],
    industryRecognition: ["RegTech leader", "AI-powered compliance", "Real-time screening", "Global coverage"]
  },
  {
    id: 59,
    company: "Complyport Ltd",
    expertise: ["Regulatory Compliance", "FCA Authorisation", "Financial Crime"],
    interests: ["RegTech", "Compliance consulting", "AML services"],
    avatar: "CMP",
    bio: "UK's largest independent compliance consultancy established in 2001, providing regulatory advisory and authorisation services to financial services firms with 1,500+ successful FCA applications and RegTech solutions",
    marketSegments: ["Banks", "Payment institutions", "Fintechs", "Investment firms"],
    geographicFocus: ["UK", "EU", "Middle East", "Asia"],
    solutionTypes: ["Compliance Consulting", "Regulatory Advisory", "RegTech Platform"],
    deliveryModels: ["Consulting services", "Outsourced compliance", "Technology solutions"],
    employeeCount: "75",
    recentInitiatives: ["ComplyPortal RegTech platform", "Financial promotions gateway", "Consumer duty implementation", "ICARA expertise"],
    partnershipEcosystem: ["FCA Skilled Panel", "APCC member", "Financial institutions", "RegTech providers"],
    regulatoryExpertise: ["FCA authorisation", "PRA regulation", "AML/KYC", "SM&CR", "MIFIDPRU"],
    industryRecognition: ["1,500+ FCA applications", "FCA Skilled Panel", "22 years experience", "700+ ongoing clients"]
  },
  {
    id: 60,
    company: "Corpay",
    expertise: ["B2B Payments", "Fleet Cards", "Expense Management"],
    interests: ["AP automation", "Virtual cards", "Cross-border payments"],
    avatar: "CPY",
    bio: "Global S&P 500 corporate payments leader processing billions of transactions across 80+ countries, providing fuel cards, commercial cards, AP automation and cross-border payment solutions to businesses worldwide",
    marketSegments: ["Corporates", "Fleet operators", "Government", "SMEs"],
    geographicFocus: ["Global", "US", "UK", "Europe", "Americas"],
    solutionTypes: ["Commercial Cards", "AP Automation", "Expense Management"],
    deliveryModels: ["Fuel cards", "Virtual cards", "SaaS platform", "Integrated solutions"],
    employeeCount: "10000+",
    recentInitiatives: ["Corpay One platform", "Select fleet cards", "E-Payables expansion", "Cross-border solutions"],
    partnershipEcosystem: ["Mastercard", "Fifth Third Bank", "Fuel networks", "Technology partners"],
    regulatoryExpertise: ["Payment regulations", "Multi-jurisdictional compliance", "Card scheme rules"],
    industryRecognition: ["#1 B2B Mastercard issuer", "S&P 500", "Global fintech leader", "80+ countries"]
  },
  {
    id: 61,
    company: "Cosegic",
    expertise: ["Payment Solutions", "Technology Consulting", "Financial Services"],
    interests: ["Payment innovation", "Digital transformation", "Consulting services"],
    avatar: "CSG",
    bio: "Specialist consulting firm providing payment solutions and technology advisory to financial services sector, supporting banks and payment companies with strategic transformation and implementation projects",
    marketSegments: ["Banks", "Payment providers", "Financial institutions"],
    geographicFocus: ["UK", "Europe"],
    solutionTypes: ["Consulting Services", "Payment Solutions", "Technology Advisory"],
    deliveryModels: ["Management consulting", "Implementation support", "Strategic advisory"],
    employeeCount: "50-100",
    recentInitiatives: ["Payment transformation", "Digital consulting", "Technology implementation"],
    partnershipEcosystem: ["Banks", "Payment providers", "Technology vendors"],
    regulatoryExpertise: ["Payment regulations", "Industry standards", "Compliance frameworks"],
    industryRecognition: ["Payment specialist", "Financial services consultant"]
  },
  {
    id: 62,
    company: "Crown Agents Bank",
    expertise: ["Correspondent Banking", "Emerging Markets", "Cross-border Payments"],
    interests: ["Frontier markets", "Development finance", "Payment corridors"],
    avatar: "CAB",
    bio: "UK-licensed bank specialising in emerging and frontier markets, providing correspondent banking, payment services and treasury solutions to financial institutions, NGOs and governments across 180+ countries",
    marketSegments: ["Banks", "NGOs", "Governments", "Development agencies"],
    geographicFocus: ["Global", "Emerging markets", "Frontier markets", "Africa", "Asia"],
    solutionTypes: ["Correspondent Banking", "Payment Services", "Treasury Solutions"],
    deliveryModels: ["Banking services", "Payment processing", "Currency services"],
    employeeCount: "100-250",
    recentInitiatives: ["Digital transformation", "Payment corridor expansion", "Emerging market focus", "Compliance enhancement"],
    partnershipEcosystem: ["Correspondent banks", "Development agencies", "NGOs", "Payment providers"],
    regulatoryExpertise: ["UK banking regulations", "Correspondent banking", "Emerging market compliance", "Sanctions frameworks"],
    industryRecognition: ["Emerging markets specialist", "180+ countries", "Development finance expert", "Correspondent bank"]
  },
  {
    id: 63,
    company: "Currencies Direct",
    expertise: ["Foreign Exchange", "International Payments", "Currency Services"],
    interests: ["FX solutions", "Cross-border transfers", "Currency risk"],
    avatar: "CD",
    bio: "Leading international payments and currency exchange specialist, helping businesses and individuals transfer money overseas with competitive rates and expert service across 40+ currencies",
    marketSegments: ["SMEs", "Corporates", "Individuals", "Property buyers"],
    geographicFocus: ["UK", "Europe", "Global"],
    solutionTypes: ["FX Services", "International Payments", "Currency Management"],
    deliveryModels: ["Online platform", "Relationship management", "API services"],
    employeeCount: "250-500",
    recentInitiatives: ["Digital platform enhancement", "Business solutions expansion", "Currency risk management", "Technology investment"],
    partnershipEcosystem: ["Banks", "Payment providers", "Property platforms", "Business networks"],
    regulatoryExpertise: ["FCA authorisation", "Payment regulations", "AML compliance", "Multi-jurisdictional licensing"],
    industryRecognition: ["FX specialist", "40+ currencies", "Award-winning service", "30+ years experience"]
  },
  {
    id: 64,
    company: "D8 Corporation",
    expertise: ["Payment Technology", "Software Solutions", "Digital Payments"],
    interests: ["Payment innovation", "Technology platforms", "Digital solutions"],
    avatar: "D8",
    bio: "Technology solutions provider delivering innovative payment and digital commerce platforms to financial institutions and businesses, specialising in modern payment infrastructure and software development",
    marketSegments: ["Financial institutions", "Payment providers", "Merchants"],
    geographicFocus: ["UK", "Europe", "Global"],
    solutionTypes: ["Payment Platform", "Software Solutions", "Technology Services"],
    deliveryModels: ["Software development", "Platform services", "Technology consulting"],
    employeeCount: "50-100",
    recentInitiatives: ["Payment platform development", "Digital commerce solutions", "Technology partnerships"],
    partnershipEcosystem: ["Financial institutions", "Payment providers", "Technology vendors"],
    regulatoryExpertise: ["Payment regulations", "Technology compliance", "Security standards"],
    industryRecognition: ["Payment technology specialist", "Software development expert"]
  },
  {
    id: 65,
    company: "DECTA",
    expertise: ["Payment Processing", "Card Issuing", "Acquiring Solutions"],
    interests: ["Digital payments", "E-wallets", "Payment innovation"],
    avatar: "DCT",
    bio: "International payment processing company providing full-cycle card issuing, acquiring and digital wallet solutions to banks and payment institutions across Europe and beyond with modern API-based platform",
    marketSegments: ["Banks", "Payment institutions", "E-money providers", "Fintechs"],
    geographicFocus: ["Europe", "UK", "Global"],
    solutionTypes: ["Card Processing", "Issuing Platform", "Acquiring Services"],
    deliveryModels: ["Processing services", "White-label solutions", "API platform"],
    employeeCount: "500-1000",
    recentInitiatives: ["Digital wallet solutions", "API platform expansion", "European growth", "Technology modernisation"],
    partnershipEcosystem: ["Card schemes", "Banks", "Payment providers", "Technology partners"],
    regulatoryExpertise: ["European payment regulations", "Card scheme compliance", "PCI-DSS", "Multi-country licensing"],
    industryRecognition: ["European processor", "Full-cycle solutions", "Innovation awards", "Regional expertise"]
  },
  {
    id: 66,
    company: "Deloitte",
    expertise: ["Professional Services", "Consulting", "Financial Advisory"],
    interests: ["Digital transformation", "Payment modernisation", "RegTech"],
    avatar: "DLT",
    bio: "Big Four professional services giant with extensive financial services and payments practice, advising banks and payment providers on strategy, technology transformation and regulatory compliance across 150+ countries",
    marketSegments: ["Banks", "Payment providers", "Fintechs", "Corporates"],
    geographicFocus: ["Global", "UK", "Europe", "Americas", "Asia Pacific"],
    solutionTypes: ["Consulting", "Audit Services", "Technology Advisory"],
    deliveryModels: ["Professional services", "Implementation", "Advisory"],
    employeeCount: "457000+",
    recentInitiatives: ["Payment transformation programmes", "Open banking advisory", "Digital banking strategy", "RegTech solutions"],
    partnershipEcosystem: ["Financial institutions", "Regulators", "Technology providers", "Industry bodies"],
    regulatoryExpertise: ["Banking regulations", "Payment frameworks", "Audit standards", "Global compliance"],
    industryRecognition: ["Big Four", "Global leader", "150+ countries", "457,000 professionals"]
  },
  {
    id: 67,
    company: "Dialect",
    expertise: ["Payment Solutions", "Technology Services", "Digital Payments"],
    interests: ["Payment innovation", "Technology platforms", "Financial services"],
    avatar: "DIA",
    bio: "Technology solutions provider specialising in payment and financial services platforms, delivering innovative solutions to banks and payment companies for digital transformation and payment modernisation",
    marketSegments: ["Banks", "Payment providers", "Financial institutions"],
    geographicFocus: ["UK", "Europe"],
    solutionTypes: ["Payment Platform", "Technology Solutions", "Professional Services"],
    deliveryModels: ["Software solutions", "Technology consulting", "Implementation services"],
    employeeCount: "10-50",
    recentInitiatives: ["Payment platform development", "Digital transformation", "Technology partnerships"],
    partnershipEcosystem: ["Financial institutions", "Payment providers", "Technology vendors"],
    regulatoryExpertise: ["Payment regulations", "Technology compliance", "Industry standards"],
    industryRecognition: ["Payment technology specialist", "Financial services innovator"]
  },
  {
    id: 68,
    company: "Discover Global Network",
    expertise: ["Card Network", "Payment Processing", "Merchant Services"],
    interests: ["Global expansion", "Network partnerships", "Digital payments"],
    avatar: "DGN",
    bio: "Global payment network with extensive acceptance footprint, providing card issuing and acquiring services through partnerships and alliances, connecting merchants and cardholders across 200+ countries and territories",
    marketSegments: ["Banks", "Card issuers", "Merchants", "Payment providers"],
    geographicFocus: ["Global", "US", "UK", "Europe", "Asia Pacific"],
    solutionTypes: ["Card Network", "Processing Services", "Merchant Acquiring"],
    deliveryModels: ["Network services", "Processing platform", "Partnership model"],
    employeeCount: "5000+",
    recentInitiatives: ["Network expansion", "Partnership development", "Digital innovation", "Global acceptance growth"],
    partnershipEcosystem: ["Banks", "Payment networks", "Merchants", "Technology providers"],
    regulatoryExpertise: ["Card scheme rules", "Payment regulations", "Global compliance", "Network standards"],
    industryRecognition: ["Major card network", "200+ countries", "Global partnerships", "Extensive acceptance"]
  },
  {
    id: 69,
    company: "Dojo",
    expertise: ["Payment Solutions", "Merchant Services", "Point-of-Sale"],
    interests: ["SME payments", "Digital commerce", "Technology innovation"],
    avatar: "DJO",
    bio: "Fast-growing UK payment solutions provider delivering all-in-one card machines, payment processing and business management tools to independent businesses and SMEs with transparent pricing and modern technology",
    marketSegments: ["SMEs", "Retail", "Hospitality", "Service businesses"],
    geographicFocus: ["UK", "Ireland"],
    solutionTypes: ["Payment Terminal", "Merchant Services", "Business Tools"],
    deliveryModels: ["Hardware and software", "Subscription model", "Integrated solutions"],
    employeeCount: "500-1000",
    recentInitiatives: ["Rapid growth expansion", "Product innovation", "SME focus", "Technology development"],
    partnershipEcosystem: ["Card schemes", "Acquiring banks", "Software providers", "Business networks"],
    regulatoryExpertise: ["FCA regulation", "Payment regulations", "PCI compliance", "Merchant services"],
    industryRecognition: ["Fast-growing provider", "SME specialist", "UK market leader", "Innovation awards"]
  },
  {
    id: 70,
    company: "Ecommpay",
    expertise: ["Payment Processing", "E-commerce Solutions", "Risk Management"],
    interests: ["Online payments", "Alternative payment methods", "Fraud prevention"],
    avatar: "ECP",
    bio: "International payment service provider offering comprehensive e-commerce payment processing, alternative payment methods and risk management solutions to online merchants across global markets with local expertise",
    marketSegments: ["E-commerce", "Online merchants", "Digital businesses", "Marketplaces"],
    geographicFocus: ["Global", "UK", "Europe", "Asia", "Americas"],
    solutionTypes: ["Payment Gateway", "Processing Services", "Risk Management"],
    deliveryModels: ["API platform", "Payment orchestration", "Managed services"],
    employeeCount: "500-1000",
    recentInitiatives: ["Alternative payment methods", "Global expansion", "Risk technology", "Open banking integration"],
    partnershipEcosystem: ["Card schemes", "Alternative payment methods", "E-commerce platforms", "Technology providers"],
    regulatoryExpertise: ["Payment regulations", "Multi-jurisdictional licensing", "PCI-DSS", "Data protection"],
    industryRecognition: ["E-commerce specialist", "Global coverage", "APM expertise", "Risk management leader"]
  }
]